(() => {
'use strict';
const $=id=>document.getElementById(id);
const tabs=[...document.querySelectorAll('.tab')],uploadPanel=$('uploadPanel'),urlPanel=$('urlPanel');
const videoInput=$('videoInput'),fileName=$('fileName'),urlInput=$('urlInput');
const goal=$('goal'),experimentName=$('experimentName'),hookInput=$('hookInput'),caption=$('caption'),cta=$('cta');
const analyzeBtn=$('analyzeBtn'),status=$('status'),results=$('results'),summary=$('summary'),metrics=$('metrics'),findings=$('findings');
const hooks=$('hooks'),captionSuggestion=$('captionSuggestion'),captionReason=$('captionReason'),hashtags=$('hashtags');
const ctaSuggestion=$('ctaSuggestion'),timingText=$('timingText'),timingOptions=$('timingOptions'),experimentText=$('experimentText');
const resetBtn=$('resetBtn'),saveExperimentBtn=$('saveExperimentBtn'),copyExperimentBtn=$('copyExperimentBtn');
const copyCaptionBtn=$('copyCaptionBtn'),copyHashtagsBtn=$('copyHashtagsBtn'),copyCtaBtn=$('copyCtaBtn'),instagramBtn=$('instagramBtn');
const history=$('history'),historyList=$('historyList'),clearHistoryBtn=$('clearHistoryBtn');
const STORAGE_KEY='reellab.experiments.v4',MAX_HISTORY=12;
let mode='upload',selectedFile=null,videoMeta=null,lastAnalysis=null;
const goalNames={reach:'دیده‌شدن',followers:'فالوور',engagement:'تعامل',sales:'فروش'};
const setStatus=(t,tone='')=>{status.textContent=t;status.dataset.tone=tone;};
const formatDuration=s=>{if(!Number.isFinite(s))return'—';s=Math.round(s);return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;};
const getVideoMeta=file=>new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),v=document.createElement('video');v.preload='metadata';v.onloadedmetadata=()=>{const m={duration:v.duration,width:v.videoWidth,height:v.videoHeight};URL.revokeObjectURL(u);resolve(m);};v.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('VIDEO_METADATA'));};v.src=u;});
const isInstagramReel=value=>{try{const u=new URL(value);return/(^|\.)instagram\.com$/i.test(u.hostname)&&/\/(reels?|p)\//i.test(u.pathname);}catch{return false;}};
const addFinding=(title,text,kind='warn')=>{const box=document.createElement('article');box.className=`finding ${kind}`;const b=document.createElement('b');b.textContent=title;const p=document.createElement('p');p.textContent=text;box.append(b,p);findings.appendChild(box);};
const addMetric=(label,value)=>{const box=document.createElement('div');box.className='metric';const b=document.createElement('b');b.textContent=value;const s=document.createElement('span');s.textContent=label;box.append(b,s);metrics.appendChild(box);};
const addHook=(label,text,recommended=false)=>{const box=document.createElement('div');box.className=`hook${recommended?' recommended':''}`;const small=document.createElement('small');small.textContent=label;const span=document.createElement('span');span.textContent=text;box.append(small,span);if(recommended){const use=document.createElement('button');use.type='button';use.className='use-btn';use.textContent='انتخاب این قلاب';use.onclick=()=>{hookInput.value=text;document.querySelectorAll('.hook').forEach(x=>x.classList.remove('chosen'));box.classList.add('chosen');setStatus('قلاب انتخاب شد؛ دوباره تحلیل کن تا کپشن هم با همین قلاب ساخته شود.','ok');};box.append(use);}hooks.appendChild(box);};
const addChip=text=>{const chip=document.createElement('span');chip.className='hashtag';chip.textContent=text;hashtags.appendChild(chip);};
const readHistory=()=>{try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(d)?d.slice(0,MAX_HISTORY):[];}catch{return[];}};
const writeHistory=items=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(items.slice(0,MAX_HISTORY)));return true;}catch{setStatus('ذخیره محلی ممکن نشد.','error');return false;}};
const renderHistory=()=>{const items=readHistory();history.hidden=!items.length;historyList.textContent='';items.forEach(item=>{const card=document.createElement('article');card.className='history-card';const h=document.createElement('div');h.className='history-head';const title=document.createElement('strong');title.textContent=item.name||'آزمایش بدون نام';const date=document.createElement('small');date.textContent=new Date(item.createdAt).toLocaleString('fa-IR');h.append(title,date);card.append(h);const meta=document.createElement('p');meta.className='history-meta';meta.textContent=`${goalNames[item.goal]||item.goal} • ${item.duration?formatDuration(item.duration):'بدون ویدیو'} • ${item.topic||'موضوع نامشخص'}`;card.append(meta);const plan=document.createElement('p');plan.className='history-plan';plan.textContent=item.experiment;card.append(plan);const outcome=document.createElement('input');outcome.className='field';outcome.placeholder='نتیجه واقعی بعد از انتشار (ویو/لایک/ذخیره...)';outcome.value=item.outcome||'';outcome.onchange=()=>{const all=readHistory(),f=all.find(x=>x.id===item.id);if(f){f.outcome=outcome.value.trim();writeHistory(all);}};card.append(outcome);const note=document.createElement('textarea');note.rows=2;note.placeholder='چه چیزی یاد گرفتی؟';note.value=item.note||'';note.onchange=()=>{const all=readHistory(),f=all.find(x=>x.id===item.id);if(f){f.note=note.value.trim();writeHistory(all);}};card.append(note);const remove=document.createElement('button');remove.className='ghost danger';remove.textContent='حذف این آزمایش';remove.onclick=()=>{writeHistory(readHistory().filter(x=>x.id!==item.id));renderHistory();};card.append(remove);historyList.appendChild(card);});};
const copyText=async(text,button)=>{const clean=String(text||'').trim();if(!clean){setStatus('چیزی برای کپی وجود ندارد.','error');return false;}let ok=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(clean);ok=true;}}catch{}if(!ok){const a=document.createElement('textarea');a.value=clean;a.setAttribute('readonly','');a.style.position='fixed';a.style.left='-9999px';document.body.appendChild(a);a.focus();a.select();try{ok=document.execCommand('copy');}catch{}a.remove();}if(ok){const old=button.textContent;button.textContent='✓ کپی شد';setStatus('کپی شد.','ok');setTimeout(()=>button.textContent=old,1400);}else setStatus('کپی خودکار مسدود شد؛ متن را دستی کپی کن.','error');return ok;};
const loadScript=src=>new Promise((resolve,reject)=>{const old=document.querySelector(`script[data-reellab-src="${src}"]`);if(old){old.dataset.loaded==='1'?resolve():old.addEventListener('load',resolve,{once:true});return;}const s=document.createElement('script');s.src=src;s.async=true;s.dataset.reellabSrc=src;s.onload=()=>{s.dataset.loaded='1';resolve();};s.onerror=()=>reject(new Error('SCRIPT_LOAD'));document.head.appendChild(s);});
const sampleFrames=async(file,count=7)=>{const u=URL.createObjectURL(file),v=document.createElement('video');v.src=u;v.muted=true;v.playsInline=true;await new Promise((r,j)=>{v.onloadedmetadata=r;v.onerror=j;});const frames=[];for(let i=0;i<count;i++){const t=Math.min(Math.max(0.05,(v.duration||1)*(i/(count-1))),Math.max(0.05,(v.duration||1)-0.05));v.currentTime=t;await new Promise(r=>{let done=false;const finish=()=>{if(!done){done=true;r();}};v.onseeked=finish;setTimeout(finish,1200);});const c=document.createElement('canvas');const scale=Math.min(1,720/v.videoWidth);c.width=Math.max(1,Math.round(v.videoWidth*scale));c.height=Math.max(1,Math.round(v.videoHeight*scale));c.getContext('2d').drawImage(v,0,0,c.width,c.height);frames.push({canvas:c,time:t});}URL.revokeObjectURL(u);return frames;};
const visualObjects=async frames=>{try{if(!window.cocoSsd){await loadScript('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.22.0/dist/tf.min.js');await loadScript('https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd@2.2.3/dist/coco-ssd.min.js');}if(!window.cocoSsd)return[];const model=await window.cocoSsd.load({base:'lite_mobilenet_v2'}),hits=[];for(const f of frames){const preds=await model.detect(f.canvas);preds.filter(p=>p.score>=0.60).forEach(p=>hits.push(p.class));}return[...new Set(hits)];}catch{return[];}};
const readOcr=async frames=>{try{await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.min.js');if(!window.Tesseract)return'';const worker=await window.Tesseract.createWorker('fas+eng');let out='';for(const f of frames.slice(0,5)){const r=await worker.recognize(f.canvas);out+=` ${r.data.text||''}`;}await worker.terminate();return out.replace(/\s+/g,' ').trim();}catch{return'';}};
const transcribeAudio=async file=>{try{const mod=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1/+esm');const pipe=await mod.pipeline('automatic-speech-recognition','onnx-community/whisper-tiny',{dtype:'q4',device:'wasm'});const buf=await file.arrayBuffer();const ac=new AudioContext();const decoded=await ac.decodeAudioData(buf.slice(0));const ch=decoded.numberOfChannels;const len=decoded.length;const mono=new Float32Array(len);for(let i=0;i<len;i++){let v=0;for(let c=0;c<ch;c++)v+=decoded.getChannelData(c)[i]||0;mono[i]=v/ch;}const step=Math.max(1,Math.round(decoded.sampleRate/16000));const audio=new Float32Array(Math.ceil(len/step));for(let i=0,j=0;i<len;i+=step,j++)audio[j]=mono[i];const out=await pipe(audio,{sampling_rate:16000,chunk_length_s:20,stride_length_s:3});await ac.close();return String(out?.text||'').replace(/\s+/g,' ').trim();}catch{return'';}};
const aliases={car:'خودرو',truck:'کامیون',bus:'اتوبوس',motorcycle:'موتورسیکلت',bicycle:'دوچرخه',person:'آدم',dog:'سگ',cat:'گربه',cell_phone:'موبایل',laptop:'لپ‌تاپ',tv:'تلویزیون',book:'کتاب',bottle:'بطری',cup:'لیوان',chair:'صندلی',backpack:'کوله‌پشتی',handbag:'کیف',suitcase:'چمدان',sports_ball:'توپ',cake:'کیک',pizza:'پیتزا',banana:'موز',apple:'سیب'};
const topicRules=[
[['پژو','پراید','سمند','دنا','تیبا','خودرو','ماشین','car','motorcycle'],'خودرو و ماشین',['#خودرو','#ماشین','#خرید_خودرو','#خودروی_کارکرده']],
[['غذا','آشپزی','رستوران','پیتزا','کیک','pizza','cake','banana','apple'],'غذا و آشپزی',['#غذا','#آشپزی','#غذای_خونگی','#فود']],
[['ورزش','تمرین','فیتنس','بدنسازی','gym','sports_ball'],'ورزش و فیتنس',['#ورزش','#فیتنس','#تمرین','#بدنسازی']],
[['موبایل','گوشی','تکنولوژی','لپ‌تاپ','لپ تاپ','گجت','cell_phone','laptop'],'موبایل و تکنولوژی',['#موبایل','#تکنولوژی','#گجت','#ترفند_موبایل']],
[['پول','درآمد','کسب و کار','کسب‌وکار','اقتصاد','سرمایه','فروش'],'کسب‌وکار و درآمد',['#کسب_و_کار','#درآمد','#فروش','#اقتصاد']],
[['سفر','گردشگری','ایرانگردی','چمدان','ساحل','هتل','suitcase'],'سفر و گردشگری',['#سفر','#گردشگری','#ایرانگردی','#مسافرت']],
[['آموزش','یادگیری','آموز','tutorial','excel','اکسل'],'آموزش و یادگیری',['#آموزش','#یادگیری','#نکات_کاربردی','#آموزش_آنلاین']],
[['لباس','استایل','مد','فشن','کیف','handbag'],'مد و استایل',['#استایل','#مد','#فشن','#لباس']]
];
const cleanText=t=>String(t||'').replace(/\b\d{5,}\b/g,' ').replace(/\s+/g,' ').trim();
const inferTopic=(text,objects)=>{const t=cleanText(text).toLowerCase();const objectText=objects.map(x=>aliases[x]||x).join(' ').toLowerCase();const all=`${t} ${objectText}`.trim();let best=null,bestScore=0;for(const [keys,name,tags] of topicRules){let score=0;for(const k of keys){if(all.includes(k.toLowerCase()))score+=k.length>=5?2:1;}if(score>bestScore){bestScore=score;best={name,tags};}}if(!best)return{name:'موضوع دقیق تشخیص داده نشد',tags:[],confidence:'پایین'};return{name:best.name,tags:best.tags,confidence:bestScore>=4?'بالا':'متوسط'};};
const humanize=s=>String(s||'').replace(/می‌باشد/g,'ه').replace(/می‌گردد/g,'می‌شه').replace(/می‌تواند/g,'می‌تونه').replace(/استفاده کنید/g,'استفاده کن').replace(/انجام دهید/g,'انجام بده');
const makeHooks=(g,topic,signal)=>{if(signal){const s=signal.length>90?signal.slice(0,90).trim()+'…':signal;return[`اول اینو ببین: ${s}`,`یه نکته مهم درباره ${topic}: ${s}`,`اگه ${topic} برات مهمه، این قسمت رو از دست نده`];}if(topic==='موضوع دقیق تشخیص داده نشد')return['۳ ثانیه اول را با یک جمله مشخص و واقعی شروع کن','اول نتیجه را بگو، بعد توضیح بده','با یک سؤال مستقیم شروع کن که دقیقاً به محتوای ویدیو مربوط باشد'];const s=topic;return g==='sales'?[`قبل از خرید ${s} اینو ببین`,`این اشتباه درباره ${s} می‌تونه گرون تموم بشه`,`اگه قصد خرید ${s} داری، این نکته رو چک کن`]:g==='followers'?[`اگه ${s} برات مهمه، اینو ببین`,`یه نکته کاربردی درباره ${s} که بد نیست بدونی`,`قبل از رد کردن، این نکته درباره ${s} رو ببین`]:g==='engagement'?[`تو درباره ${s} چه نظری داری؟`,`یه سؤال درباره ${s}: تو کدومو انتخاب می‌کنی؟`,`این قسمت ${s} رو ببین و نظرتو بگو`]:[`این نکته درباره ${s} رو قبل از رد کردن ببین`,`اگه ${s} برات مهمه، این قسمت رو از دست نده`,`یه نکته درباره ${s} که شاید تا حالا نشنیده باشی`];};
const makeCaption=(g,cap,hook,topic,signal)=>{if(cap.trim().length>=40)return cap.trim();const first=cleanText(signal||'');let body=first?`توی این ویدیو درباره ${topic} صحبت می‌کنم و نکته اصلیش رو کوتاه می‌گم.`:`این ویدیو درباره ${topic}ـه و نکته اصلی رو کوتاه و خودمونی می‌گم.`;if(topic==='موضوع دقیق تشخیص داده نشد')body='موضوع ویدیو هنوز با اطمینان کافی تشخیص داده نشده؛ این متن را کورکورانه منتشر نکن و اول یک توضیح کوتاه از موضوع به سایت بده.';const action=g==='followers'?'اگه این مدل محتوا به دردت می‌خوره، پیج رو دنبال کن.':g==='engagement'?'تو چی فکر می‌کنی؟ نظرتو توی کامنت بگو.':g==='sales'?'اگه سؤال داری، همین‌جا بپرس.':'اگه فکر می‌کنی به درد یکی دیگه هم می‌خوره، براش بفرست.';return`${humanize(hook||'یه نکته کوتاه و کاربردی 👇')}\n\n${body}\n\n${action}`;};
const topicTags=(topic,text)=>{const base=topicRules.find(x=>x[1]===topic)?.[2]||[];if(!base.length)return['#ریلز'];const words=cleanText(text).toLowerCase().match(/[\p{L}]{4,}/gu)||[];const stop=new Set(['این','برای','است','که','یک','های','با','در','را','رو','من','تو','هم','از','تا','روی','درباره','ویدیو']);const extras=[];for(const w of words){if(stop.has(w)||w.length<4)continue;const h=`#${w}`;if(!base.includes(h)&&!extras.includes(h))extras.push(h);if(extras.length>=2)break;}return[...new Set([...base,...extras])].slice(0,6);};
const ctaFor=g=>g==='followers'?'اگه این مدل محتوا به دردت می‌خوره، پیج رو دنبال کن.':g==='engagement'?'تو چی فکر می‌کنی؟ نظرتو توی کامنت بگو.':g==='sales'?'اگه سؤال داری، همین‌جا بپرس.':'اگه فکر می‌کنی به درد یکی دیگه هم می‌خوره، براش بفرست.';
const timingPlan=()=>{const h=readHistory();const valid=h.map(x=>x.outcome||'').filter(Boolean);if(valid.length>=4)return{title:'زمان شخصی‌سازی‌شده',text:'حالا وقتشه ساعت‌ها را با نتیجه واقعی آزمایش‌های خودت مقایسه کنی؛ سایت از روی عددهای ثبت‌شده بازه بهتر را پیشنهاد می‌دهد.',options:['نتایج ۴ آزمایش اخیر را با ساعت انتشارشان مقایسه کن.','یک ساعت ثابت را در چند پست تست کن تا مقایسه معنی‌دار شود.']};return{title:'زمان پیشنهادی برای تست',text:'چون هنوز داده کافی از پیجت نداریم، ساعت زیر «بهترین ساعت» نیست؛ فقط یک نقطه شروع برای آزمایش است.',options:['امشب: ۲۰:۳۰ (آزمایش پایه)','اگر مخاطب شب‌ها فعال نیست: ۱۲:۳۰ (آزمایش دوم)']};};
const visualQuality=frames=>{if(!frames.length)return{scene:'نامشخص',motion:'نامشخص'};const vals=frames.map(f=>{const d=f.canvas.getContext('2d').getImageData(0,0,f.canvas.width,f.canvas.height).data;let sum=0,n=0;for(let i=0;i<d.length;i+=32){sum+=(d[i]+d[i+1]+d[i+2])/3;n++;}return sum/n;});const spread=Math.max(...vals)-Math.min(...vals);return{scene:spread>35?'تغییر صحنه محسوس':'تغییر صحنه کم',motion:spread>55?'پر‌تحرک':'نسبتاً یکنواخت'};};
tabs.forEach(tab=>tab.onclick=()=>{mode=tab.dataset.mode;tabs.forEach(t=>{const a=t===tab;t.classList.toggle('active',a);t.setAttribute('aria-selected',String(a));});uploadPanel.hidden=mode!=='upload';urlPanel.hidden=mode!=='url';setStatus('');});
videoInput.onchange=async()=>{selectedFile=videoInput.files?.[0]||null;videoMeta=null;if(!selectedFile){fileName.textContent='ویدیو روی سرور آپلود نمی‌شود؛ تحلیل در مرورگر انجام می‌شود.';return;}fileName.textContent=selectedFile.name;if(!selectedFile.type.startsWith('video/')){selectedFile=null;videoInput.value='';setStatus('فایل انتخاب‌شده ویدیو نیست.','error');return;}try{videoMeta=await getVideoMeta(selectedFile);setStatus(`ویدیو آماده است • ${formatDuration(videoMeta.duration)} • ${videoMeta.width}×${videoMeta.height}`,'ok');}catch{setStatus('خواندن مشخصات ویدیو ممکن نشد.','error');}};
analyzeBtn.onclick=async()=>{if(mode==='url'&&!selectedFile){if(!isInstagramReel(urlInput.value)){setStatus('لینک Instagram Reel معتبر نیست.','error');return;}setStatus('لینک ثبت شد؛ برای تحلیل واقعی محتوا فایل ویدیو را هم انتخاب کن.','error');return;}if(!selectedFile){setStatus('اول ویدیو را انتخاب کن.','error');return;}setStatus('در حال تحلیل واقعی Reel… چند مرحله دارد.');analyzeBtn.disabled=true;results.hidden=true;try{if(!videoMeta)videoMeta=await getVideoMeta(selectedFile);const frameCount=Math.min(8,Math.max(5,Math.ceil(videoMeta.duration/8)));const frames=await sampleFrames(selectedFile,frameCount);setStatus('۱/۴ بررسی تصویر و متن روی ویدیو…');const [ocr,objects]=await Promise.all([readOcr(frames),visualObjects(frames)]);setStatus('۲/۴ گوش دادن به صدای ویدیو و استخراج متن…');const transcript=await transcribeAudio(selectedFile);setStatus('۳/۴ تشخیص موضوع و ساخت پیشنهادها…');const combined=`${caption.value} ${hookInput.value} ${ocr} ${transcript}`.trim();const topic=inferTopic(combined,objects);const visual=visualQuality(frames);const signal=cleanText(transcript||ocr);const hookSignal=signal.split(/[.!؟\n]/).map(x=>x.trim()).find(x=>x.length>=8)||'';const hookList=makeHooks(goal.value,topic.name,hookSignal);const tagList=topicTags(topic.name,`${transcript} ${ocr}`);const suggestedCaption=makeCaption(goal.value,caption.value,hookInput.value.trim(),topic.name,signal);const ctaText=cta.value.trim()||ctaFor(goal.value);const timing=timingPlan();lastAnalysis={topic:topic.name,tags:tagList,objects,ocr,transcript,experiment:experimentName.value.trim(),goal:goal.value,duration:videoMeta.duration,captionLength:caption.value.length,hasCta:!!cta.value.trim(),hook:hookList[0]};
summary.textContent=`موضوع تشخیص‌داده‌شده: ${topic.name} • اطمینان ${topic.confidence} • تحلیل تصویر، OCR${transcript?' و گفتار':''} در مرورگر انجام شد.`;metrics.textContent='';addMetric('مدت ویدیو',formatDuration(videoMeta.duration));addMetric('قاب',videoMeta.height>=videoMeta.width?'عمودی ✓':'غیرعمودی');addMetric('متن کپشن',`${caption.value.length} کاراکتر`);addMetric('گفتار تشخیص‌داده‌شده',transcript?`${transcript.length} کاراکتر`:'یافت نشد');addMetric('متن روی تصویر',ocr?`${ocr.length} کاراکتر`:'یافت نشد');addMetric('اشیای دیده‌شده',objects.length?objects.length:'—');
findings.textContent='';if(videoMeta.duration>45)addFinding('🟡 ویدیو نسبتاً طولانی است','خودِ طول ویدیو مشکل قطعی نیست؛ ریتم و شروع را با یک نسخه کوتاه‌تر مقایسه کن.','warn');else addFinding('🟢 مدت ویدیو','از نظر طول، هشدار جدی نداریم.','good');if(videoMeta.height<videoMeta.width)addFinding('🔴 قاب نامناسب','نسخه عمودی 9:16 برای Reel آماده کن.','bad');else addFinding('🟢 قاب ویدیو','ویدیو عمودی است.','good');if(hookInput.value.trim())addFinding('🟡 قلاب فعلی وارد شده','سایت آن را با پیشنهادهای محتوایی مقایسه می‌کند؛ انتخاب نهایی با خودت است.','warn');else if(hookSignal)addFinding('🟢 قلاب از گفتار/متن استخراج شد',`شروع محتوایی پیدا شد: «${hookSignal.slice(0,180)}»`,'good');else addFinding('🔴 قلاب واقعی پیدا نشد','از ۱ تا ۳ ثانیه اول متن یا گفتار قابل اتکا پیدا نشد؛ قلاب را خودت مشخص کن.','bad');if(!caption.value.trim())addFinding('🔴 کپشن فعلی خالی است','کپشن پیشنهادی پایین از سیگنال واقعی ویدیو ساخته شده؛ اگر موضوع درست تشخیص داده نشده، منتشرش نکن.','bad');if(!cta.value.trim())addFinding('🟡 CTA نداری',`برای این هدف: ${ctaText}`,'warn');if(transcript)addFinding('🎙️ گفتار ویدیو شناسایی شد',transcript.slice(0,320),'good');if(ocr)addFinding('🔎 متن روی ویدیو شناسایی شد',ocr.slice(0,260),'good');if(objects.length)addFinding('👁️ عناصر تصویری شناسایی‌شده',objects.map(x=>aliases[x]||x).join('، '),'good');if(topic.confidence==='پایین')addFinding('🔴 موضوع با اطمینان کافی مشخص نشد','برای جلوگیری از هشتگ و کپشن اشتباه، سایت موضوع حدسی تولید نکرده است. یک جمله درباره موضوع Reel وارد کن یا متن/قلاب واقعی را اضافه کن.','bad');
hooks.textContent='';hookList.forEach((x,i)=>addHook(i?'گزینه '+(i+1):'قلاب پیشنهادی',x,i===0));captionReason.textContent=`این پیشنهاد از ${transcript?'گفتار ویدیو':'متن قابل‌خواندن ویدیو'} و سیگنال‌های واقعی تحلیل ساخته شده؛ متن عمومی و اسم فایل وارد کپشن نمی‌شود.`;captionSuggestion.textContent=suggestedCaption;hashtags.textContent='';tagList.forEach(addChip);ctaSuggestion.textContent=ctaText;timingText.textContent=timing.text;timingOptions.textContent='';timing.options.forEach(x=>{const d=document.createElement('div');d.className='timing-option';d.textContent=x;timingOptions.appendChild(d);});experimentText.textContent=`فقط یک متغیر را عوض کن: قلاب. موضوع «${topic.name}» و بقیه موارد را تا حد ممکن ثابت نگه دار؛ نتیجه واقعی را بعد از انتشار ثبت کن.`;results.hidden=false;results.scrollIntoView({behavior:'smooth',block:'start'});setStatus('تحلیل محتوایی کامل شد.','ok');}catch(e){console.error(e);setStatus('تحلیل کامل نشد. اگر موتور صوتی روی گوشی در دسترس نبود، تحلیل تصویر/OCR باید به‌تنهایی هم نتیجه بدهد.','error');}finally{analyzeBtn.disabled=false;}};
copyCaptionBtn.onclick=()=>copyText(captionSuggestion.textContent,copyCaptionBtn);copyHashtagsBtn.onclick=()=>copyText([...hashtags.querySelectorAll('.hashtag')].map(x=>x.textContent).join(' '),copyHashtagsBtn);copyCtaBtn.onclick=()=>copyText(ctaSuggestion.textContent,copyCtaBtn);
saveExperimentBtn.onclick=()=>{if(!lastAnalysis){setStatus('اول تحلیل را اجرا کن.','error');return;}const all=readHistory();all.unshift({id:Date.now(),createdAt:new Date().toISOString(),name:lastAnalysis.experiment||'آزمایش Reel',goal:lastAnalysis.goal,duration:lastAnalysis.duration,captionLength:lastAnalysis.captionLength,hasCta:lastAnalysis.hasCta,topic:lastAnalysis.topic,experiment:experimentText.textContent,outcome:'',note:''});writeHistory(all);renderHistory();setStatus('آزمایش ذخیره شد.','ok');};
copyExperimentBtn.onclick=()=>copyText(`موضوع: ${lastAnalysis?.topic||'—'}\nقلاب: ${hookInput.value||lastAnalysis?.hook||'یکی از پیشنهادها'}\nکپشن: ${captionSuggestion.textContent}\nهشتگ: ${[...hashtags.querySelectorAll('.hashtag')].map(x=>x.textContent).join(' ')}\nCTA: ${ctaSuggestion.textContent}\nزمان تست: ${[...timingOptions.querySelectorAll('.timing-option')].map(x=>x.textContent).join(' | ')}`,copyExperimentBtn);
resetBtn.onclick=()=>{results.hidden=true;findings.textContent='';setStatus('تحلیل جدید آماده است.','ok');};instagramBtn.onclick=()=>window.open('https://www.instagram.com/','_blank','noopener,noreferrer');clearHistoryBtn.onclick=()=>{localStorage.removeItem(STORAGE_KEY);renderHistory();};
renderHistory();
})();