(() => {
'use strict';
const $=id=>document.getElementById(id);
const tabs=[...document.querySelectorAll('.tab')],uploadPanel=$('uploadPanel'),urlPanel=$('urlPanel');
const videoInput=$('videoInput'),fileName=$('fileName'),urlInput=$('urlInput');
const goal=$('goal'),experimentName=$('experimentName'),hookInput=$('hookInput'),caption=$('caption'),cta=$('cta');
const analyzeBtn=$('analyzeBtn'),status=$('status'),results=$('results'),summary=$('summary'),metrics=$('metrics'),findings=$('findings');
const hooks=$('hooks'),captionSuggestion=$('captionSuggestion'),captionReason=$('captionReason'),hashtags=$('hashtags');
const ctaSuggestion=$('ctaSuggestion'),timingText=$('timingText'),timingOptions=$('timingOptions'),experimentText=$('experimentText');
const resetBtn=$('resetBtn'),saveExperimentBtn=$('saveExperimentBtn'),copyExperimentBtn=$('copyExperimentBtn');
const copyCaptionBtn=$('copyCaptionBtn'),copyHashtagsBtn=$('copyHashtagsBtn'),copyCtaBtn=$('copyCtaBtn'),instagramBtn=$('instagramBtn');
const history=$('history'),historyList=$('historyList'),clearHistoryBtn=$('clearHistoryBtn');
const STORAGE_KEY='reellab.experiments.v3',MAX_HISTORY=12;
let mode='upload',selectedFile=null,videoMeta=null,lastAnalysis=null;
const goalNames={reach:'دیده‌شدن',followers:'فالوور',engagement:'تعامل',sales:'فروش'};
const setStatus=(t,tone='')=>{status.textContent=t;status.dataset.tone=tone;};
const formatDuration=s=>{if(!Number.isFinite(s))return'—';s=Math.round(s);return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;};
const getVideoMeta=file=>new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),v=document.createElement('video');v.preload='metadata';v.onloadedmetadata=()=>{const m={duration:v.duration,width:v.videoWidth,height:v.videoHeight};URL.revokeObjectURL(u);resolve(m);};v.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('VIDEO_METADATA'));};v.src=u;});
const isInstagramReel=value=>{try{const u=new URL(value);return/(^|\.)instagram\.com$/i.test(u.hostname)&&/\/reels?\//i.test(u.pathname);}catch{return false;}};
const addFinding=(title,text,kind='warn')=>{const box=document.createElement('article');box.className=`finding ${kind}`;const b=document.createElement('b');b.textContent=title;const p=document.createElement('p');p.textContent=text;box.append(b,p);findings.appendChild(box);};
const addMetric=(label,value)=>{const box=document.createElement('div');box.className='metric';const b=document.createElement('b');b.textContent=value;const s=document.createElement('span');s.textContent=label;box.append(b,s);metrics.appendChild(box);};
const addHook=(label,text,recommended=false)=>{const box=document.createElement('div');box.className=`hook${recommended?' recommended':''}`;const small=document.createElement('small');small.textContent=label;const span=document.createElement('span');span.textContent=text;box.append(small,span);if(recommended){const use=document.createElement('button');use.type='button';use.className='use-btn';use.textContent='انتخاب این قلاب';use.onclick=()=>{hookInput.value=text;document.querySelectorAll('.hook').forEach(x=>x.classList.remove('chosen'));box.classList.add('chosen');setStatus('این قلاب انتخاب شد؛ حالا کپشن و تحلیل را دوباره اجرا کن.','ok');};box.append(use);}hooks.appendChild(box);};
const addChip=text=>{const chip=document.createElement('span');chip.className='hashtag';chip.textContent=text;hashtags.appendChild(chip);};
const readHistory=()=>{try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(d)?d.slice(0,MAX_HISTORY):[];}catch{return[];}};
const writeHistory=items=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(items.slice(0,MAX_HISTORY)));return true;}catch{setStatus('ذخیره محلی ممکن نشد.','error');return false;}};
const renderHistory=()=>{const items=readHistory();history.hidden=!items.length;historyList.textContent='';items.forEach(item=>{const card=document.createElement('article');card.className='history-card';const h=document.createElement('div');h.className='history-head';const title=document.createElement('strong');title.textContent=item.name||'آزمایش بدون نام';const date=document.createElement('small');date.textContent=new Date(item.createdAt).toLocaleString('fa-IR');h.append(title,date);card.append(h);const meta=document.createElement('p');meta.className='history-meta';meta.textContent=`${goalNames[item.goal]||item.goal} • ${item.duration?formatDuration(item.duration):'بدون ویدیو'} • ${item.topic||'موضوع نامشخص'}`;card.append(meta);const plan=document.createElement('p');plan.className='history-plan';plan.textContent=item.experiment;card.append(plan);const outcome=document.createElement('input');outcome.className='field';outcome.placeholder='نتیجه بعد از انتشار';outcome.value=item.outcome||'';outcome.onchange=()=>{const all=readHistory(),f=all.find(x=>x.id===item.id);if(f){f.outcome=outcome.value.trim();writeHistory(all);}};card.append(outcome);const note=document.createElement('textarea');note.rows=2;note.placeholder='چه چیزی یاد گرفتی؟';note.value=item.note||'';note.onchange=()=>{const all=readHistory(),f=all.find(x=>x.id===item.id);if(f){f.note=note.value.trim();writeHistory(all);}};card.append(note);const remove=document.createElement('button');remove.className='ghost danger';remove.textContent='حذف این آزمایش';remove.onclick=()=>{writeHistory(readHistory().filter(x=>x.id!==item.id));renderHistory();};card.append(remove);historyList.appendChild(card);});};
const copyText=async(text,button)=>{const clean=String(text||'').trim();if(!clean){setStatus('چیزی برای کپی وجود ندارد.','error');return false;}let ok=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(clean);ok=true;}}catch{}if(!ok){const a=document.createElement('textarea');a.value=clean;a.setAttribute('readonly','');a.style.position='fixed';a.style.left='-9999px';document.body.appendChild(a);a.focus();a.select();try{ok=document.execCommand('copy');}catch{}a.remove();}if(ok){const old=button.textContent;button.textContent='✓ کپی شد';setStatus('کپی شد.','ok');setTimeout(()=>button.textContent=old,1400);}else setStatus('کپی خودکار مسدود شد؛ متن را دستی کپی کن.','error');return ok;};
const loadScript=src=>new Promise((resolve,reject)=>{const old=document.querySelector(`script[data-reellab-src="${src}"]`);if(old){old.dataset.loaded==='1'?resolve():old.addEventListener('load',resolve,{once:true});return;}const s=document.createElement('script');s.src=src;s.async=true;s.dataset.reellabSrc=src;s.onload=()=>{s.dataset.loaded='1';resolve();};s.onerror=()=>reject(new Error('SCRIPT_LOAD'));document.head.appendChild(s);});
const sampleFrames=async(file,count=5)=>{const u=URL.createObjectURL(file),v=document.createElement('video');v.src=u;v.muted=true;v.playsInline=true;await new Promise((r,j)=>{v.onloadedmetadata=r;v.onerror=j;});const frames=[];const times=[];for(let i=0;i<count;i++)times.push(Math.min(Math.max(0.15,(v.duration||1)*(i/(count-1))),Math.max(0.15,(v.duration||1)-0.05)));for(const t of times){v.currentTime=t;await new Promise(r=>{v.onseeked=r;setTimeout(r,800);});const c=document.createElement('canvas');const scale=Math.min(1,640/v.videoWidth);c.width=Math.max(1,Math.round(v.videoWidth*scale));c.height=Math.max(1,Math.round(v.videoHeight*scale));c.getContext('2d').drawImage(v,0,0,c.width,c.height);frames.push({canvas:c,time:t});}URL.revokeObjectURL(u);return frames;};
const objectAliases={car:['خودرو','ماشین'],truck:['کامیون'],bus:['اتوبوس'],motorcycle:['موتورسیکلت'],bicycle:['دوچرخه'],person:['آدم','شخص'],dog:['سگ'],cat:['گربه'],cell_phone:['موبایل','گوشی'],laptop:['لپ‌تاپ'],tv:['تلویزیون'],book:['کتاب'],bottle:['بطری'],cup:['لیوان'],chair:['صندلی'],backpack:['کوله'],handbag:['کیف'],suitcase:['چمدان'],sports_ball:['ورزش'],cake:['کیک'],pizza:['پیتزا'],banana:['موز'],apple:['سیب']};
const visualObjects=async frames=>{try{if(!window.cocoSsd){await loadScript('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.22.0/dist/tf.min.js');await loadScript('https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd@2.2.3/dist/coco-ssd.min.js');}if(!window.cocoSsd)return[];const model=await window.cocoSsd.load({base:'lite_mobilenet_v2'}),hits=[];for(const f of frames){const preds=await model.detect(f.canvas);preds.filter(p=>p.score>=0.55).forEach(p=>hits.push(p.class));}return[...new Set(hits)];}catch{return[];}};
const readOcr=async frames=>{try{await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.min.js');if(!window.Tesseract)return'';const worker=await window.Tesseract.createWorker('fas+eng');let out='';for(const f of frames.slice(0,4)){const r=await worker.recognize(f.canvas);out+=` ${r.data.text||''}`;}await worker.terminate();return out.replace(/\s+/g,' ').trim();}catch{return'';}};
const topicRules=[
[['پژو','پراید','سمند','دنا','تیبا','خودرو','ماشین','car','motorcycle'],'خودرو و خرید/بررسی ماشین',['#خودرو','#ماشین','#خرید_خودرو','#خودروی_کارکرده']],
[['غذا','آشپزی','رستوران','پیتزا','کیک','pizza','cake','banana','apple'],'غذا و آشپزی',['#غذا','#آشپزی','#آشپزی_آسان','#فود']],
[['ورزش','تمرین','فیتنس','gym','sports_ball'],'ورزش و فیتنس',['#ورزش','#فیتنس','#تمرین','#سلامتی']],
[['موبایل','گوشی','تکنولوژی','لپ‌تاپ','لپ تاپ','cell_phone','laptop'],'موبایل و تکنولوژی',['#موبایل','#تکنولوژی','#گجت','#ترفند_موبایل']],
[['پول','درآمد','کسب و کار','اقتصاد','سرمایه','فروش'],'کسب‌وکار و درآمد',['#کسب_و_کار','#درآمد','#فروش','#اقتصاد']],
[['سفر','گردشگری','ایرانگردی','چمدان','ساحل'],'سفر و گردشگری',['#سفر','#گردشگری','#ایرانگردی','#مسافرت']],
[['آموزش','یادگیری','آموز','tutorial','excel','اکسل'],'آموزش و یادگیری',['#آموزش','#یادگیری','#نکات_کاربردی','#آموزش_آنلاین']],
[['لباس','استایل','مد','فشن','کیف'],'مد و استایل',['#استایل','#مد','#فشن','#لباس']]
];
const inferTopic=(text,objects)=>{const t=`${text} ${objects.join(' ')}`.toLowerCase();for(const [keys,name,tags] of topicRules){if(keys.some(k=>t.includes(k)))return{name,tags,confidence:objects.length||text? 'بالا':'متوسط'};}return{name:text.trim()?'بر اساس متن Reel':'موضوع نامشخص',tags:['#ریلز','#اینستاگرام','#محتوای_فارسی'],confidence:text.trim()?'متوسط':'پایین'};};
const makeHooks=(g,topic)=>{const s=topic&&topic!=='موضوع نامشخص'?topic:'این موضوع';if(g==='sales')return[`قبل از خرید/انتخاب ${s} این نکته رو ببین`,`این اشتباه موقع ${s} می‌تونه گرون تموم بشه`,`اگر قصد ${s} داری، این ۳ نکته رو چک کن`];if(g==='followers')return[`اگر ${s} برات مهمه، این نکته رو از دست نده`,`قبل از رد کردن، این نکته درباره ${s} رو ببین`,`این اشتباه درباره ${s} رو خیلی‌ها انجام می‌دن`];if(g==='engagement')return[`تو درباره ${s} کدوم گزینه رو انتخاب می‌کنی؟`,`یک اشتباه رایج درباره ${s} که باید دید`,`تا آخر ببین؛ آخرش درباره ${s} یک سؤال دارم`];return[`قبل از رد کردن، این نکته درباره ${s} رو ببین`,`اگر ${s} برات مهمه، این ۱۰ ثانیه رو از دست نده`,`چیزی که خیلی‌ها درباره ${s} نمی‌دونن`];};
const makeCaption=(g,cap,hook,topic)=>{const open=hook||`یک نکته مهم درباره ${topic} 👇`;const body=cap.trim().length>=30?cap.trim():`در این Reel یک نکته کاربردی درباره ${topic} می‌بینی. اگر برات مفید بود، ذخیره‌اش کن تا بعداً دوباره ببینی.`;const action=g==='followers'?'برای نکته‌های بعدی صفحه را دنبال کن.':g==='engagement'?'نظرت را در کامنت بنویس.':g==='sales'?'اگر سؤال داری، قبل از تصمیم‌گیری در کامنت بپرس.':'اگر برای یک نفر دیگر هم مفید است، برایش بفرست.';return`${open}\n\n${body}\n\n${action}`;};
const topicTags=(topic,text)=>{const base=topicRules.find(x=>x[1]===topic)?.[2]||[];const generic=['#ریلز','#اینستاگرام'];const words=text.toLowerCase().match(/[\p{L}\p{N}]{4,}/gu)||[];const extras=[];for(const w of words.slice(0,12))if(!['این','برای','است','که','یک','های','با','در','را'].includes(w))extras.push(`#${w.replace(/[^\p{L}\p{N}_]/gu,'')}`);return[...new Set([...base,...extras,...generic])].filter(x=>x.length>2).slice(0,8);};
const ctaFor=g=>g==='followers'?'برای نکته‌های بعدی صفحه را دنبال کن.':g==='engagement'?'نظرت را در کامنت بنویس؛ تو کدام را انتخاب می‌کنی؟':g==='sales'?'اگر سؤال داری، در کامنت بپرس.':'اگر برای یک نفر دیگر هم مفید است، برایش بفرست.';
const visualQuality=frames=>{if(!frames.length)return{scene:'نامشخص',motion:'نامشخص'};const vals=frames.map(f=>{const d=f.canvas.getContext('2d').getImageData(0,0,f.canvas.width,f.canvas.height).data;let sum=0;for(let i=0;i<d.length;i+=16)sum+=(d[i]+d[i+1]+d[i+2])/3;return sum/(d.length/16);});const spread=Math.max(...vals)-Math.min(...vals);return{scene:spread>35?'تغییر صحنه محسوس':'تغییر صحنه کم',motion:spread>55?'پر‌تحرک':'نسبتاً یکنواخت'};};
tabs.forEach(tab=>tab.onclick=()=>{mode=tab.dataset.mode;tabs.forEach(t=>{const a=t===tab;t.classList.toggle('active',a);t.setAttribute('aria-selected',String(a));});uploadPanel.hidden=mode!=='upload';urlPanel.hidden=mode!=='url';setStatus('');});
videoInput.onchange=async()=>{selectedFile=videoInput.files?.[0]||null;videoMeta=null;if(!selectedFile){fileName.textContent='ویدیو روی سرور آپلود نمی‌شود؛ تحلیل در مرورگر انجام می‌شود.';return;}fileName.textContent=selectedFile.name;if(!selectedFile.type.startsWith('video/')){selectedFile=null;videoInput.value='';setStatus('فایل انتخاب‌شده ویدیو نیست.','error');return;}try{videoMeta=await getVideoMeta(selectedFile);setStatus(`ویدیو آماده است • ${formatDuration(videoMeta.duration)} • ${videoMeta.width}×${videoMeta.height}`,'ok');}catch{setStatus('خواندن مشخصات ویدیو ممکن نشد.','error');}};
analyzeBtn.onclick=async()=>{if(mode==='url'&&!selectedFile){if(!isInstagramReel(urlInput.value)){setStatus('لینک Instagram Reel معتبر نیست.','error');return;}setStatus('برای تحلیل واقعی محتوا، فایل ویدیو را هم انتخاب کن. لینک Instagram در MVP دانلود نمی‌شود.','error');return;}if(!selectedFile){setStatus('اول ویدیو را انتخاب کن.','error');return;}setStatus('در حال تحلیل واقعی محتوای Reel… چند لحظه صبر کن.');analyzeBtn.disabled=true;results.hidden=true;try{if(!videoMeta)videoMeta=await getVideoMeta(selectedFile);const frames=await sampleFrames(selectedFile,Math.min(6,Math.max(4,Math.ceil(videoMeta.duration/12))));setStatus('در حال تشخیص متن روی تصویر و موضوع…');const [ocr,objects]=await Promise.all([readOcr(frames),visualObjects(frames)]);const userText=`${caption.value} ${hookInput.value} ${selectedFile.name}`.trim();const topic=inferTopic(`${userText} ${ocr}`,objects);const q=visualQuality(frames);const allText=`${userText} ${ocr} ${objects.join(' ')}`;const tagList=topicTags(topic.name,allText);const hooksList=makeHooks(goal.value,topic.name);const suggestedCaption=makeCaption(goal.value,caption.value,hookInput.value.trim(),topic.name);const ctaText=cta.value.trim()||ctaFor(goal.value);lastAnalysis={topic:topic.name,tags:tagList,objects,ocr,experiment:experimentName.value.trim(),goal:goal.value,duration:videoMeta.duration,captionLength:caption.value.length,hasCta:!!cta.value.trim()};
summary.textContent=`موضوع تشخیص‌داده‌شده: ${topic.name} • اطمینان ${topic.confidence} • تحلیل محتوایی در مرورگر انجام شد.`;metrics.textContent='';addMetric('مدت ویدیو',formatDuration(videoMeta.duration));addMetric('قاب',videoMeta.height>=videoMeta.width?'عمودی ✓':'غیرعمودی');addMetric('متن کپشن',`${caption.value.length} کاراکتر`);addMetric('متن تشخیص‌داده‌شده',ocr?`${ocr.length} کاراکتر`:'یافت نشد');addMetric('اشیای دیده‌شده',objects.length?objects.length:'—');
findings.textContent='';if(videoMeta.duration>45)addFinding('🟡 ویدیو نسبتاً طولانی است','برای دیده‌شدن، شروع و ریتم را جداگانه تست کن؛ طول به‌تنهایی دلیل رد کردن نیست.','warn');else addFinding('🟢 مدت ویدیو','طول به‌تنهایی مشکل واضحی ایجاد نکرد؛ تمرکز اصلی را روی شروع و ارزش محتوا بگذار.','good');if(videoMeta.height<videoMeta.width)addFinding('🔴 قاب نامناسب','نسخه 9:16 عمودی بساز تا فضای Reel بهتر استفاده شود.','bad');else addFinding('🟢 قاب ویدیو','قاب عمودی برای Reel مناسب است.','good');if(!hookInput.value.trim()&&!ocr.trim())addFinding('🔴 قلاب متنی قابل تشخیص نیست','سایت متن قلاب را از فریم‌های شروع پیدا نکرد. یک جمله مشخص در ۱ تا ۳ ثانیه اول اجرا کن.','bad');else addFinding('🟢 شروع قابل بررسی است','از متن واردشده/متن روی تصویر برای پیشنهاد قلاب استفاده شد.','good');if(!caption.value.trim())addFinding('🔴 کپشن نداری','کپشن پیشنهادی پایین بر اساس موضوع تشخیص‌داده‌شده ساخته شده؛ قبل از کپی یک بار محتوایش را با Reel تطبیق بده.','bad');if(!cta.value.trim())addFinding('🟡 CTA نداری',`برای هدف ${goalNames[goal.value]} این CTA را امتحان کن: ${ctaText}`,'warn');if(ocr)addFinding('🔎 متن روی ویدیو شناسایی شد',ocr.slice(0,260),'good');if(objects.length)addFinding('👁️ عناصر تصویری شناسایی‌شده',objects.map(x=>objectAliases[x]?.join(' / ')||x).join('، '),'good');
 hooks.textContent='';hooksList.forEach((x,i)=>addHook(i?'گزینه '+(i+1):'قلاب اصلی',x,i===0));captionReason.textContent=`موضوع Reel از ترکیب متن کپشن/قلاب/نام فایل، متن روی فریم‌ها و اشیای قابل تشخیص استخراج شد. ${ocr?'OCR فعال بود.':'متن واضحی روی فریم‌ها پیدا نشد.'}`;captionSuggestion.textContent=suggestedCaption;hashtags.textContent='';tagList.forEach(addChip);ctaSuggestion.textContent=ctaText;timingText.textContent='ReelLab عمداً ساعت ثابت اعلام نمی‌کند؛ بدون داده واقعی مخاطبان، ساعت مشخص قابل اتکا نیست.';timingOptions.textContent='';const noTime=document.createElement('div');noTime.className='timing-option';noTime.textContent='فعلاً زمان انتشار را با داده Insights خودت انتخاب کن؛ بعد از ثبت نتایج آزمایش‌ها می‌توانیم بازه شخصی‌سازی‌شده بسازیم.';timingOptions.appendChild(noTime);experimentText.textContent=`یک متغیر را تست کن: «قلاب» را عوض کن و موضوع ${topic.name} را ثابت نگه دار؛ سپس نتیجه واقعی انتشار را در آزمایش‌ها ثبت کن.`;results.hidden=false;results.scrollIntoView({behavior:'smooth',block:'start'});setStatus('تحلیل محتوایی تمام شد.','ok');}catch(e){console.error(e);setStatus('تحلیل کامل نشد؛ مشخصات پایه ویدیو را بررسی کن و دوباره امتحان کن.','error');}finally{analyzeBtn.disabled=false;}};
copyCaptionBtn.onclick=()=>copyText(captionSuggestion.textContent,copyCaptionBtn);copyHashtagsBtn.onclick=()=>copyText([...hashtags.querySelectorAll('.hashtag')].map(x=>x.textContent).join(' '),copyHashtagsBtn);copyCtaBtn.onclick=()=>copyText(ctaSuggestion.textContent,copyCtaBtn);
saveExperimentBtn.onclick=()=>{if(!lastAnalysis){setStatus('اول تحلیل را اجرا کن.','error');return;}const all=readHistory();all.unshift({id:Date.now(),createdAt:new Date().toISOString(),name:lastAnalysis.experiment||'آزمایش Reel',goal:lastAnalysis.goal,duration:lastAnalysis.duration,captionLength:lastAnalysis.captionLength,hasCta:lastAnalysis.hasCta,topic:lastAnalysis.topic,experiment:experimentText.textContent,outcome:'',note:''});writeHistory(all);renderHistory();setStatus('آزمایش ذخیره شد.','ok');};
copyExperimentBtn.onclick=()=>copyText(`موضوع: ${lastAnalysis?.topic||'—'}\nقلاب: ${hookInput.value||'یکی از پیشنهادها'}\nکپشن: ${captionSuggestion.textContent}\nهشتگ: ${[...hashtags.querySelectorAll('.hashtag')].map(x=>x.textContent).join(' ')}\nCTA: ${ctaSuggestion.textContent}\nزمان: فعلاً بر اساس Insights واقعی پیج انتخاب شود.`,copyExperimentBtn);
resetBtn.onclick=()=>{results.hidden=true;setStatus('تحلیل جدید آماده است.','ok');};instagramBtn.onclick=()=>window.open('https://www.instagram.com/','_blank','noopener,noreferrer');clearHistoryBtn.onclick=()=>{localStorage.removeItem(STORAGE_KEY);renderHistory();};
renderHistory();
})();