(()=>{
'use strict';
const $=id=>document.getElementById(id), norm=s=>String(s??'').replace(/\s+/g,' ').trim(), low=s=>norm(s).toLowerCase();
const UNKNOWN='موضوع دقیق تشخیص داده نشد';
const topics=[
{keys:['ماشین','خودرو','پژو','پراید','سمند','دنا','تیبا','رانندگی','motorcycle','motorbike','car','truck','bus'],name:'خودرو و ماشین',tags:['#خودرو','#ماشین','#رانندگی','#خرید_خودرو']},
{keys:['غذا','آشپزی','رستوران','پیتزا','کیک','دسر','غذاخوری','pizza','cake','food','cooking','restaurant'],name:'غذا و آشپزی',tags:['#غذا','#آشپزی','#فود','#غذای_خونگی']},
{keys:['ورزش','تمرین','فیتنس','بدنسازی','باشگاه','توپ','gym','fitness','workout','sports'],name:'ورزش و فیتنس',tags:['#ورزش','#فیتنس','#تمرین','#بدنسازی']},
{keys:['موبایل','گوشی','تکنولوژی','لپ‌تاپ','لپ تاپ','گجت','اپلیکیشن','اندروید','آیفون','iphone','android','phone','laptop','technology','tech'],name:'موبایل و تکنولوژی',tags:['#تکنولوژی','#موبایل','#گجت','#ترفند_موبایل']},
{keys:['پول','درآمد','کسب و کار','کسب‌وکار','اقتصاد','سرمایه','فروش','بازاریابی','مشتری','business','money','sales'],name:'کسب‌وکار و درآمد',tags:['#کسب_و_کار','#درآمد','#فروش','#بازاریابی']},
{keys:['سفر','گردشگری','ایرانگردی','هتل','ساحل','طبیعت','مسافرت','گردش','travel','tourism','beach','hotel'],name:'سفر و گردشگری',tags:['#سفر','#گردشگری','#ایرانگردی','#مسافرت']},
{keys:['آموزش','یادگیری','آموز','اکسل','نکته','tutorial','learn','education','excel','lesson'],name:'آموزش و یادگیری',tags:['#آموزش','#یادگیری','#نکات_کاربردی','#آموزش_آنلاین']},
{keys:['لباس','استایل','مد','فشن','آرایش','میکاپ','زیبایی','fashion','style','makeup','beauty','dress'],name:'مد و زیبایی',tags:['#استایل','#مد','#فشن','#زیبایی']},
{keys:['گیم','بازی','گیمر','game','gaming','controller','video game'],name:'بازی و گیم',tags:['#گیم','#بازی','#گیمر']},
{keys:['کتاب','فیلم','سریال','موسیقی','آهنگ','movie','music','book','concert'],name:'سرگرمی و فرهنگ',tags:['#سرگرمی','#موسیقی','#فیلم']}
];
const objectAliases={person:'آدم',car:'خودرو',truck:'کامیون',bus:'اتوبوس',motorcycle:'موتورسیکلت',bicycle:'دوچرخه',cell_phone:'موبایل',laptop:'لپ‌تاپ',tv:'تلویزیون',book:'کتاب',bottle:'بطری',cup:'لیوان',chair:'صندلی',backpack:'کوله‌پشتی',handbag:'کیف',suitcase:'چمدان',sports_ball:'توپ',cake:'کیک',pizza:'پیتزا',banana:'موز',apple:'سیب',dog:'سگ',cat:'گربه'};
const cleanSpeech=s=>{let t=norm(s).replace(/\[(?:music|noise|applause|laughter|silence|blank)[^\]]*\]/gi,' ');t=t.replace(/\b(?:music|instrumental|applause|laughter)\b/gi,' ');const w=t.split(/\s+/).filter(Boolean),o=[];for(const x of w)if(!o.length||low(o[o.length-1])!==low(x))o.push(x);t=norm(o.join(' '));const letters=(t.match(/[\p{L}]/gu)||[]).length;if(t.length<12||letters/Math.max(1,t.length)<.52)return'';if(/^(yeah|yes|no|oh|uh|um|hmm|i swear)(?:\s+(yeah|yes|no|oh|uh|um|hmm|i swear))*[.!?]*$/i.test(t))return'';return t;};
const cleanOcr=s=>{const w=norm(s).split(/\s+/).filter(x=>x.length>=2&&/[\p{L}]/u.test(x)),o=[];for(const x of w)if(!o.some(y=>low(y)===low(x)))o.push(x);const t=o.join(' ');if(o.length<3||new Set(o.map(low)).size/o.length<.55)return'';return t;};
function detect(manual,speech,ocr,vision,objects){
 const m=norm(manual);if(m.length>=4){const hit=topics.find(t=>t.keys.some(k=>low(m).includes(low(k))));return{name:hit?.name||m.slice(0,70),tags:hit?.tags||['#ریلز','#اینستاگرام'],confidence:hit?'بالا':'متوسط',known:true,source:'توضیح مستقیم کاربر'};}
 const objectText=objects.map(x=>objectAliases[x]||x).join(' ');const all=low(`${speech} ${ocr} ${vision} ${objectText}`);let best=null,bestScore=0;
 for(const t of topics){let s=0;for(const k of t.keys){if(all.includes(low(k)))s+=k.length>=5?2:1;}if(s>bestScore){bestScore=s;best=t;}}
 if(!best||bestScore<3)return{name:UNKNOWN,tags:[],confidence:'پایین',known:false,source:'سیگنال کافی وجود ندارد'};
 return{name:best.name,tags:best.tags,confidence:bestScore>=6?'بالا':'متوسط',known:true,source:vision?'ترکیب گفتار/متن/تصویر':'ترکیب گفتار/متن'};
}
function readSignals(){const r=$('results');if(!r)return{speech:'',ocr:'',objects:[]};const text=r.innerText||'';const sm=text.match(/گفتار تشخیص‌داده‌شده\s*([\s\S]*?)(?=\n\s*(?:متن روی ویدیو|متن روی تصویر|👁️|عناصر تصویری))/i);const om=text.match(/(?:متن روی ویدیو|متن روی تصویر)\s*([\s\S]*?)(?=\n\s*(?:👁️|عناصر تصویری|🟢|🔴|🟡))/i);const obj=text.match(/عناصر تصویری شناسایی‌شده\s*([\s\S]*?)(?=\n\s*(?:🔴|🟡|🟢|HOOK|CAPTION|HASHTAGS))/i);return{speech:cleanSpeech(sm?.[1]||''),ocr:cleanOcr(om?.[1]||''),objects:(obj?.[1]||'').split(/[،,•]/).map(norm).filter(Boolean)};}
const signalForHook=(speech,vision)=>{const s=norm(speech||vision);if(!s)return'';return s.length>110?s.slice(0,110).replace(/[،,;:]+[^،,;:]*$/,'').trim()+'…':s;};
function makeHooks(goal,topic,signal){const t=topic.name;if(signal&&topic.known)return[`این نکته درباره ${t} رو قبل از رد کردن ببین: ${signal}`,`اگه ${t} برات مهمه، این قسمت رو از دست نده: ${signal}`,`یه نکته واقعی درباره ${t}: ${signal}`];if(!topic.known)return['موضوع واقعی و قلاب این Reel را از همان اتفاق ۳ ثانیه اول بساز.','نتیجه یا اتفاق اصلی را قبل از مقدمه نشان بده.','یک سؤال مشخص درباره اتفاق واقعی ویدیو بپرس.'];if(goal==='sales')return[`قبل از خرید ${t} اینو ببین`,`این اشتباه درباره ${t} می‌تونه گرون تموم بشه`,`اگه قصد خرید ${t} داری، این نکته رو چک کن`];if(goal==='followers')return[`اگه ${t} برات مهمه، اینو ببین`,`یه نکته کاربردی درباره ${t} که بد نیست بدونی`,`قبل از رد کردن، این نکته درباره ${t} رو ببین`];if(goal==='engagement')return[`تو درباره ${t} چه نظری داری؟`,`یه سؤال درباره ${t}: تو کدومو انتخاب می‌کنی؟`,`این بخش ${t} رو ببین و نظرتو بگو`];return[`قبل از رد کردن، این نکته درباره ${t} رو ببین`,`اگه ${t} برات مهمه، این قسمت رو از دست نده`,`یه نکته درباره ${t} که شاید تا حالا نشنیده باشی`];}
function makeCaption(goal,topic,hook,signal){if(!topic.known)return signal?`این Reel درباره این اتفاقه: ${signal}\n\nاگه برات جالب بود، نظرت رو بگو.`:'موضوع ویدیو هنوز با اطمینان کافی تشخیص داده نشده؛ این متن را حدسی منتشر نکن.';const end={reach:'اگه به درد یکی می‌خوره، براش بفرست.',followers:'اگه این مدل محتوا به کارت میاد، فالو کن.',engagement:'تو جای من بودی چی کار می‌کردی؟ بنویس.',sales:'اگه به کارت میاد، جزئیاتش رو ببین.'}[goal]||'نظرت رو بگو.';const lead=signal?`توی این Reel درباره ${topic.name} و این نکته صحبت می‌کنیم: ${signal}`:`توی این Reel درباره ${topic.name} صحبت می‌کنیم.`;return `${lead}\n\n${end}`;}
function score(topic,speech,ocr,vision,objects){let n=15;if(topic.known)n+=35;if(speech)n+=15;if(ocr)n+=10;if(vision)n+=15;if(objects.length)n+=5;if(norm($('hookInput')?.value))n+=5;if(norm($('caption')?.value))n+=5;return Math.min(100,n);}
function ensureFinding(text,kind){const f=$('findings');if(!f)return;[...f.querySelectorAll('article')].filter(a=>a.dataset.reellab==='intelligence').forEach(a=>a.remove());const a=document.createElement('article');a.dataset.reellab='intelligence';a.className=`finding ${kind}`;const b=document.createElement('b');b.textContent=text.title;const p=document.createElement('p');p.textContent=text.body;a.append(b,p);f.append(a);}
function setCopyState(button,available){if(!button)return;button.disabled=!available;button.dataset.ready=available?'1':'0';button.textContent=available?'📋 کپی':'📋 فعلاً متن آماده نیست';}
function bindCopy(){const capBtn=$('copyCaptionBtn'),tagBtn=$('copyHashtagsBtn'),ctaBtn=$('copyCtaBtn');if(capBtn&&!capBtn.dataset.reellabBound){capBtn.dataset.reellabBound='1';capBtn.onclick=()=>copyText($('captionSuggestion')?.textContent,capBtn);}if(tagBtn&&!tagBtn.dataset.reellabBound){tagBtn.dataset.reellabBound='1';tagBtn.onclick=()=>copyText([...($('hashtags')?.querySelectorAll('.hashtag')||[])].map(x=>x.textContent).filter(x=>x&&x[0]==='#').join(' '),tagBtn);}if(ctaBtn&&!ctaBtn.dataset.reellabBound){ctaBtn.dataset.reellabBound='1';ctaBtn.onclick=()=>copyText($('ctaSuggestion')?.textContent,ctaBtn);}}
async function copyText(text,button){const value=norm(text);if(!value||/فعلاً متن آماده نیست|هشتگ قابل اعتماد نداریم/.test(value)){setStatus('هنوز متن معتبر برای کپی آماده نیست.','error');return;}try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(value);}else throw new Error('NO_CLIPBOARD');const old=button.textContent;button.textContent='✓ کپی شد';setTimeout(()=>button.textContent=old,1400);setStatus('متن با موفقیت کپی شد.','ok');}catch{const ta=document.createElement('textarea');ta.value=value;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();let ok=false;try{ok=document.execCommand('copy');}catch{}ta.remove();if(ok){button.textContent='✓ کپی شد';setTimeout(()=>button.textContent='📋 کپی',1400);setStatus('متن با موفقیت کپی شد.','ok');}else setStatus('کپی توسط مرورگر اجازه داده نشد؛ متن را دستی انتخاب کن.','error');}}
function render(vision=''){
 const r=$('results');if(!r||r.hidden)return;const sig=readSignals();const topic=detect($('reelTopic')?.value,sig.speech,sig.ocr,vision,sig.objects);const goal=$('goal')?.value||'reach';const hook=norm($('hookInput')?.value);const signal=signalForHook(sig.speech,vision);const sc=score(topic,sig.speech,sig.ocr,vision,sig.objects);
 const metric=$('metrics');if(metric){let box=[...metric.children].find(x=>/امتیاز|آمادگی/.test(x.innerText||''));if(!box){box=document.createElement('div');box.className='metric';metric.prepend(box);}box.textContent='';const b=document.createElement('b');b.textContent=`${sc}/100`;const s=document.createElement('span');s.textContent='امتیاز آمادگی Reel';box.append(b,s);}
 const summary=$('summary');if(summary){const p=[...summary.querySelectorAll('*')].find(x=>/موضوع تشخیص‌داده‌شده:/.test(x.textContent||''));if(p)p.textContent=`موضوع تشخیص‌داده‌شده: ${topic.known?topic.name:UNKNOWN} • اطمینان ${topic.confidence} • ${topic.source}${vision?' • تحلیل تصویری هوشمند':''}`;}
 const f=$('findings');if(f){[...f.querySelectorAll('article')].filter(a=>a.dataset.reellab==='intelligence').forEach(a=>a.remove());const a=document.createElement('article');a.dataset.reellab='intelligence';a.className=`finding ${topic.known?'ok':'bad'}`;const b=document.createElement('b');b.textContent=topic.known?'🟢 موضوع قابل استفاده است':'🔴 موضوع قابل اعتماد نیست';const p=document.createElement('p');p.textContent=topic.known?`موضوع با ${topic.confidence} اطمینان از ${topic.source} استخراج شد. کپشن و هشتگ از همین سیگنال ساخته می‌شوند.`:'برای جلوگیری از کپشن و هشتگ اشتباه، موتور هنوز موضوع را قطعی نکرده است. یک جمله واقعی درباره محتوای Reel وارد کن یا اجازه بده تحلیل تصویری تکمیل شود.';a.append(b,p);f.append(a);}
 const hb=$('hooks');if(hb){hb.textContent='';makeHooks(goal,topic,signal).forEach((x,i)=>{const d=document.createElement('div');d.className=`hook${i===0?' recommended':''}`;const sm=document.createElement('small');sm.textContent=`گزینه ${i+1}`;const sp=document.createElement('span');sp.textContent=x;const btn=document.createElement('button');btn.type='button';btn.className='use-btn';btn.textContent='انتخاب این قلاب';btn.onclick=()=>{$('hookInput').value=x;document.querySelectorAll('.hook').forEach(y=>y.classList.remove('chosen'));d.classList.add('chosen');render(vision);};d.append(sm,sp,btn);hb.append(d);});}
 const cap=$('captionSuggestion');const capText=makeCaption(goal,topic,hook,signal);if(cap)cap.textContent=capText;const reason=$('captionReason');if(reason)reason.textContent=topic.known?'کپشن از سیگنال‌های معتبر Reel ساخته شده؛ اگر هوک را عوض کردی دوباره تحلیل کن.':signal?'موضوع قطعی نیست؛ این پیشنهاد فقط توصیفی است و قبل از انتشار باید خودت تأییدش کنی.':'برای جلوگیری از متن حدسی، یک جمله درباره اتفاق اصلی Reel بده.';
 const tags=$('hashtags');if(tags){tags.textContent='';const arr=topic.known?topic.tags.slice(0,5):['#ریلز','#اینستاگرام'];arr.forEach(x=>{const s=document.createElement('span');s.className='hashtag';s.textContent=x;tags.append(s);});}
 const cs=$('ctaSuggestion');if(cs)cs.textContent=norm($('cta')?.value)||({reach:'اگه به درد یکی می‌خوره، براش بفرست.',followers:'اگه این مدل محتوا به کارت میاد، فالو کن.',engagement:'تو چی فکر می‌کنی؟ توی کامنت بگو.',sales:'اگه برات مناسبه، جزئیاتش رو ببین.'}[goal]||'نظرت رو بگو.');
 bindCopy();setCopyState($('copyCaptionBtn'),!!capText&&capText.length>20&&!/^موضوع ویدیو هنوز/.test(capText));setCopyState($('copyHashtagsBtn'),topic.known);setCopyState($('copyCtaBtn'),!!norm($('ctaSuggestion')?.textContent));
}
let running=false,visionDone=false,timer=0;
async function getFrames(file,count=3){const url=URL.createObjectURL(file),v=document.createElement('video');v.src=url;v.muted=true;v.playsInline=true;await new Promise((res,rej)=>{v.onloadedmetadata=res;v.onerror=rej;});const out=[];for(let i=0;i<count;i++){v.currentTime=Math.min(Math.max(.1,v.duration*(i/(count-1))),Math.max(.1,v.duration-.1));await new Promise(res=>{let done=false;const f=()=>{if(!done){done=true;res();}};v.onseeked=f;setTimeout(f,1800);});const c=document.createElement('canvas');const scale=Math.min(1,640/v.videoWidth);c.width=Math.max(1,Math.round(v.videoWidth*scale));c.height=Math.max(1,Math.round(v.videoHeight*scale));c.getContext('2d').drawImage(v,0,0,c.width,c.height);out.push(c);}URL.revokeObjectURL(url);return out;}
async function visionCaption(file){try{const mod=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1/+esm');const pipe=await mod.pipeline('image-to-text','Xenova/vit-gpt2-image-captioning',{device:'wasm',dtype:'q4'});const frames=await getFrames(file,3);const caps=[];for(const c of frames){const out=await pipe(c,{max_new_tokens:24});const t=norm(out?.[0]?.generated_text||'');if(t&&t.length>8)caps.push(t);}return [...new Set(caps)].join(' • ');}catch{return'';}}
function run(){const r=$('results');if(!r||r.hidden||running)return;clearTimeout(timer);timer=setTimeout(async()=>{running=true;try{render('');const file=$('videoInput')?.files?.[0];if(file&&!visionDone){setStatus('تحلیل چندوجهی تصویر در حال اجراست…');const v=await visionCaption(file);visionDone=true;render(v);setStatus(v?'تحلیل هوشمند تصویر تکمیل شد.':'تحلیل پایه تکمیل شد؛ مدل تصویری در این دستگاه در دسترس نبود.','ok');}}finally{running=false;}},120);}
new MutationObserver(run).observe(document.body,{subtree:true,childList:true,characterData:true});window.addEventListener('load',()=>setTimeout(run,500));
})();