(()=>{
'use strict';
const $=id=>document.getElementById(id), text=v=>String(v??'').replace(/\s+/g,' ').trim();
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const add=(parent,tag,cls,txt)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(txt!==undefined)e.textContent=txt;parent.append(e);return e};
const getFile=()=>document.getElementById('videoInput')?.files?.[0]||null;
const getMeta=file=>new Promise((res,rej)=>{const u=URL.createObjectURL(file),v=document.createElement('video');v.preload='metadata';v.onloadedmetadata=()=>{const m={duration:v.duration,width:v.videoWidth,height:v.videoHeight};URL.revokeObjectURL(u);res(m)};v.onerror=()=>{URL.revokeObjectURL(u);rej(new Error('metadata'))};v.src=u});
const waitForSeek=v=>new Promise(resolve=>{let done=false;const finish=()=>{if(done)return;done=true;v.removeEventListener('seeked',finish);resolve()};v.addEventListener('seeked',finish,{once:true});setTimeout(finish,1200)});
async function frameStats(file,meta){const u=URL.createObjectURL(file),v=document.createElement('video');v.src=u;v.muted=true;v.playsInline=true;v.preload='auto';await new Promise((r,j)=>{v.onloadedmetadata=r;v.onerror=j});const count=Math.min(12,Math.max(6,Math.round((meta.duration||6)/3)));let prev=null,sumMotion=0,bright=[],contrast=[];for(let i=0;i<count;i++){v.currentTime=Math.min(Math.max(.05,(meta.duration||1)*i/(count-1)),Math.max(.05,(meta.duration||1)-.05));await waitForSeek(v);const c=document.createElement('canvas'),w=96,h=Math.max(54,Math.round(96*meta.height/meta.width));c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});if(!x)continue;x.drawImage(v,0,0,w,h);const p=x.getImageData(0,0,w,h).data;let b=0,b2=0;for(let j=0;j<p.length;j+=4){const y=.299*p[j]+.587*p[j+1]+.114*p[j+2];b+=y;b2+=y*y}b/=w*h;bright.push(b);contrast.push(Math.sqrt(Math.max(0,b2/(w*h)-b*b)));if(prev){let d=0;for(let j=0;j<p.length;j+=16)d+=Math.abs(p[j]-prev[j])+Math.abs(p[j+1]-prev[j+1])+Math.abs(p[j+2]-prev[j+2]);sumMotion+=d/(Math.ceil(p.length/16)*765)}prev=p}URL.revokeObjectURL(u);return{motion:count>1?sumMotion/(count-1):0,brightness:bright.length?bright.reduce((a,b)=>a+b,0)/bright.length:128,contrast:contrast.length?contrast.reduce((a,b)=>a+b,0)/contrast.length:32};}
function verdict(meta,stats){const ar=meta.width/meta.height;const vertical=ar>=.52&&ar<=.62;const dur=meta.duration;const findings=[];let score=100;if(!vertical){score-=20;findings.push(['🔴 نسبت تصویر','برای Reel عمودی 9:16 مناسب‌تر است؛ نسبت فعلی '+ar.toFixed(2)]);}else findings.push(['🟢 نسبت تصویر','نسبت تصویر با قالب عمودی Reel سازگار است.']);if(dur<5){score-=20;findings.push(['🔴 مدت ویدیو','ویدیو خیلی کوتاه است؛ پیام و قلاب ممکن است فرصت کافی نداشته باشد.']);}else if(dur>90){score-=12;findings.push(['🟠 مدت ویدیو','ویدیو طولانی است؛ حفظ توجه در طول ویدیو سخت‌تر می‌شود.']);}else findings.push(['🟢 مدت ویدیو','مدت ویدیو در محدوده قابل استفاده است.']);if(stats.brightness<35||stats.brightness>225){score-=10;findings.push(['🟠 نور تصویر','میانگین روشنایی غیرعادی است؛ خوانایی سوژه را بررسی کن.']);}else findings.push(['🟢 نور تصویر','روشنایی کلی تصویر قابل قبول است.']);if(stats.contrast<18){score-=8;findings.push(['🟠 کنتراست','کنتراست پایین است؛ سوژه ممکن است از پس‌زمینه جدا نشود.']);}else findings.push(['🟢 کنتراست','کنتراست نمونه‌های ویدیو قابل قبول است.']);if(stats.motion<.035){score-=8;findings.push(['🟠 پویایی تصویر','تغییرات فریم کم است؛ ۳ ثانیه اول را برای جذب توجه دستی بررسی کن.']);}else findings.push(['🟢 پویایی','در نمونه‌برداری فریم‌ها تغییرات تصویری قابل مشاهده است.']);return{score:clamp(score),findings};}
function textAudit(){const hook=text($('hookInput')?.value),cap=text($('caption')?.value),cta=text($('cta')?.value),topic=text($('reelTopic')?.value);let s=0,rows=[];if(hook.length>=12){s+=20;rows.push(['🟢 قلاب','قلاب وارد شده و قابل بررسی است.']);}else rows.push(['🔴 قلاب','قلاب خالی یا خیلی کوتاه است؛ موتور نباید برای آن امتیاز جعلی بسازد.']);if(cap.length>=40){s+=15;rows.push(['🟢 کپشن','کپشن برای تحلیل ساختاری به اندازه کافی متن دارد.']);}else rows.push(['🟠 کپشن','کپشن کوتاه است؛ ارزش پیشنهادی و CTA را دقیق‌تر کن.']);if(cta.length>=5){s+=10;rows.push(['🟢 CTA','دعوت به اقدام مشخص وارد شده است.']);}else rows.push(['🟠 CTA','CTA مشخص وارد نشده است.']);if(topic.length>=5){s+=15;rows.push(['🟢 موضوع','موضوع به‌صورت دستی مشخص شده و قابل اتکاتر از حدس صرف است.']);}else rows.push(['🟠 موضوع','موضوع دستی مشخص نشده؛ امتیاز متن نباید موضوع را جعل کند.']);return{score:s,rows};}
function render(meta,stats,v,ta){const r=$('results');if(!r||r.hidden)return;let card=document.getElementById('smartAudit');if(!card){card=document.createElement('article');card.id='smartAudit';card.className='tool-card';r.insertBefore(card,r.querySelector('.hook-builder')||r.firstElementChild)}card.textContent='';add(card,'p','eyebrow','REAL REEL AUDIT 🧠');add(card,'h3',null,'آنالیز چندلایه ویدیو');add(card,'p',null,'امتیاز فقط از یک حدس موضوعی ساخته نمی‌شود؛ متادیتا، فریم‌های ویدیو و ورودی‌های متنی هم‌زمان بررسی می‌شوند.');const grid=add(card,'div','metrics');add(grid,'div','metric',`${v.score}/100`);grid.lastChild.append(add(document.createElement('span'),'span',null,'کیفیت پایه ویدیو'));add(grid,'div','metric',`${Math.round(stats.motion*100)}%`);grid.lastChild.append(add(document.createElement('span'),'span',null,'تغییر فریم'));add(grid,'div','metric',`${meta.width}×${meta.height}`);grid.lastChild.append(add(grid,'span','metric',''));grid.lastChild.remove();const dims=grid.lastElementChild;dims.textContent='';dims.className='metric';add(dims,'b',null,`${meta.width}×${meta.height}`);add(dims,'span',null,'رزولوشن');add(grid,'div','metric',`${meta.duration.toFixed(1)}s`);grid.lastChild.append(add(document.createElement('span'),'span',null,'مدت'));const f=add(card,'div','findings');[...v.findings,...ta.rows].forEach(x=>{const a=add(f,'article','finding '+(x[0].startsWith('🟢')?'ok':x[0].startsWith('🔴')?'bad':'warn'));add(a,'b',null,x[0]);add(a,'p',null,x[1])});const total=clamp(Math.round(v.score+ta.score*.4));const summary=$('summary');if(summary){summary.querySelectorAll('.smart-score').forEach(x=>x.remove());const p=add(summary,'p',null,`🧠 امتیاز موتور چندلایه: ${total}/100 • این امتیاز تضمین ویو نیست؛ فقط کیفیت قابل مشاهده Reel و آمادگی انتشار را می‌سنجد.`);p.className='smart-score';}}
async function run(){const file=getFile();if(!file)return;try{const meta=await getMeta(file);if(!meta.duration||!meta.width||!meta.height)return;const stats=await frameStats(file,meta),v=verdict(meta,stats),ta=textAudit();render(meta,stats,v,ta)}catch(e){const st=$('status');if(st){st.textContent='آنالیز عمیق ویدیو کامل نشد؛ بررسی پایه بدون حدس ادامه پیدا می‌کند.';st.dataset.tone='error'}}}
const schedule=()=>{const r=$('results');if(!r)return;if(!r.hidden)run();else{const obs=new MutationObserver(()=>{if(!r.hidden){obs.disconnect();run()}});obs.observe(r,{attributes:true,attributeFilter:['hidden']});setTimeout(()=>obs.disconnect(),20000)}};
const btn=$('analyzeBtn');if(btn)btn.addEventListener('click',schedule);window.addEventListener('load',schedule);
})();
