(()=>{
'use strict';
const $=id=>document.getElementById(id),norm=s=>String(s??'').replace(/\s+/g,' ').trim(),low=s=>norm(s).toLowerCase();
const weak=/^(?:آهنگ خوبی بود|لایک کن منو|ممنون میشم فالو کنی منو|حس خوب|عالی بود|خوبه|نظر شما چیه|چه آهنگی|این آهنگ|music|song)$/i;
const topicWords=['ماشین','خودرو','پژو','پراید','سمند','دنا','رانندگی','غذا','آشپزی','رستوران','پیتزا','کیک','ورزش','تمرین','فیتنس','بدنسازی','باشگاه','موبایل','گوشی','تکنولوژی','لپ‌تاپ','گجت','اپلیکیشن','اندروید','آیفون','پول','درآمد','کسب و کار','اقتصاد','سرمایه','فروش','بازاریابی','سفر','گردشگری','ایرانگردی','هتل','طبیعت','آموزش','یادگیری','اکسل','لباس','استایل','مد','آرایش','زیبایی','گیم','بازی','گیمر','کتاب','فیلم','سریال','موسیقی','آهنگ'];
function validTopic(){const v=norm($('reelTopic')?.value);if(!v||weak.test(v)||v.length<8)return false;return topicWords.some(k=>low(v).includes(low(k)))||v.length>=18}
function garbageText(v){const t=norm(v);if(!t)return true;const toks=t.split(/\s+/).filter(Boolean);if(toks.length<4)return true;const letters=(t.match(/[\p{L}]/gu)||[]).length;const latin=(t.match(/[A-Za-z]/g)||[]).length;const single=toks.filter(x=>x.replace(/[^\p{L}\p{N}]/gu,'').length<=1).length;const weird=(t.match(/[^\p{L}\p{N}\s؟?!،؛:.'’-]/gu)||[]).length;if(letters/Math.max(1,t.length)<.55)return true;if(single/Math.max(1,toks.length)>.35)return true;if(weird/Math.max(1,t.length)>.12)return true;if(latin>8&&letters>0&&latin/Math.max(1,letters)>.55)return true;const counts={};toks.forEach(x=>counts[low(x)]=(counts[low(x)]||0)+1);if(Math.max(...Object.values(counts))/toks.length>.38)return true;if(/(?:^|\s)(?:[A-Za-z]\s*){4,}(?:$|\s)/.test(t))return true;return false}
function cleanVisibleText(){const root=$('findings');if(!root)return;for(const e of [...root.querySelectorAll('*')]){const t=norm(e.textContent);if(!t)continue;if(/^🔎\s*متن روی (?:ویدیو|تصویر)/.test(t)){e.textContent='🔎 متن معتبر روی تصویر شناسایی نشد؛ OCR نامعتبر نادیده گرفته شد.';break}if(/گفتار تشخیص‌داده‌شده/.test(t)){const body=t.replace(/^گفتار تشخیص‌داده‌شده\s*/,'');if(garbageText(body)||/\[Music\]|\bMusic\b|\bstrong man\b|\bbrave man\b|\bAN\s+RS\b/i.test(body)){e.textContent='🎙️ گفتار معتبر برای استفاده در قلاب و موضوع تشخیص داده نشد؛ رونویسی نامطمئن نادیده گرفته شد.';break}}}}
function replaceBadHook(){const hb=$('hooks');if(!hb)return;const cards=[...hb.querySelectorAll('.hook')];let bad=false;for(const c of cards){const txt=norm(c.textContent);if(garbageText(txt)||/\b(?:pe|ba|AN|RS|RCR|ERR|FERN|DEAE)\b/i.test(txt)){bad=true;break}}if(!bad)return;hb.textContent='';['قلاب واقعی را از جمله یا اتفاق مشخص Reel بساز؛ متن نامعتبر وارد قلاب نشود.','نتیجه یا اتفاق اصلی را در همان ۳ ثانیه اول نشان بده.','اگر گفتار معتبر نداری، یک جمله واقعی درباره موضوع Reel وارد کن.'].forEach((x,i)=>{const d=document.createElement('div');d.className='hook';const sm=document.createElement('small');sm.textContent='گزینه '+(i+1);const sp=document.createElement('span');sp.textContent=x;const btn=document.createElement('button');btn.type='button';btn.className='use-btn';btn.textContent='انتخاب این قلاب';btn.onclick=()=>{const h=$('hookInput');if(h){h.value=x;h.dispatchEvent(new Event('input',{bubbles:true}))}};d.append(sm,sp,btn);hb.append(d)})}
function hardenTopic(){if(validTopic())return;const summary=$('summary');if(summary){const p=[...summary.querySelectorAll('*')].find(e=>/موضوع تشخیص‌داده‌شده:/.test(e.textContent||''));if(p)p.textContent='موضوع تشخیص‌داده‌شده: موضوع دقیق تشخیص داده نشد • اطمینان پایین • سیگنال موضوعی کافی وجود ندارد.'}const f=$('findings');if(f){const a=[...f.querySelectorAll('article')].find(x=>x.dataset.reellab==='intelligence');if(a){a.className='finding bad';a.textContent='';const b=document.createElement('b');b.textContent='🔴 موضوع با اطمینان کافی مشخص نشد';const p=document.createElement('p');p.textContent='متن نامعتبر یا جمله‌های کلی مثل «آهنگ خوبی بود؟» موضوع Reel نیستند. برای کپشن و هشتگ دقیق، یک جمله واقعی درباره محتوای ویدیو وارد کن.';a.append(b,p)}}const tags=$('hashtags');if(tags){tags.textContent='';const s=document.createElement('span');s.className='hashtag';s.textContent='موضوع نامشخص — هشتگ حدسی ساخته نشد';tags.append(s)}const cs=$('captionSuggestion');if(cs){cs.textContent='برای ساخت کپشن واقعی، موضوع یا اتفاق اصلی Reel را وارد کن؛ موتور از متن حدسی استفاده نمی‌کند.'}const cr=$('captionReason');if(cr)cr.textContent='کپشن حدسی عمداً متوقف شده است چون سیگنال معتبر موضوعی وجود ندارد.';const hb=$('hooks');if(hb&&hb.children.length===0){['موضوع واقعی Reel را در ۳ ثانیه اول واضح کن.','نتیجه یا اتفاق اصلی را قبل از مقدمه نشان بده.','اگر متن یا گفتار معتبر داری، همان را به یک سؤال مشخص تبدیل کن.'].forEach((x,i)=>{const d=document.createElement('div');d.className='hook';const sm=document.createElement('small');sm.textContent='گزینه '+(i+1);const sp=document.createElement('span');sp.textContent=x;const btn=document.createElement('button');btn.type='button';btn.className='use-btn';btn.textContent='انتخاب این قلاب';btn.onclick=()=>{const h=$('hookInput');if(h){h.value=x;h.dispatchEvent(new Event('input',{bubbles:true}))}};d.append(sm,sp,btn);hb.append(d)})}}
function disableBadHashCopy(){const b=$('copyHashtagsBtn');if(b){b.disabled=true;b.textContent='📋 فعلاً هشتگ معتبر آماده نیست'}}
function protectCaption(){const c=$('captionSuggestion');if(!c)return;const t=norm(c.textContent);if(garbageText(t)||/\b(?:pe|ba|AN|RS|RCR|ERR|FERN|DEAE)\b/i.test(t)){c.textContent='برای ساخت کپشن واقعی، موضوع یا اتفاق اصلی Reel را وارد کن؛ موتور از متن حدسی استفاده نمی‌کند.';const r=$('captionReason');if(r)r.textContent='کپشن حدسی به‌دلیل نبود سیگنال معتبر متوقف شد.'}}
let busy=false,timer=0,last='';function apply(){if(busy)return;const key=[norm($('reelTopic')?.value),norm($('hookInput')?.value),norm($('caption')?.value),norm($('cta')?.value),$('results')?.innerText||''].join('|');if(key===last)return;last=key;busy=true;try{cleanVisibleText();hardenTopic();replaceBadHook();protectCaption();if(!validTopic())disableBadHashCopy()}finally{busy=false}}
function boot(){const r=$('results');if(!r)return;const mo=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(apply,100)});mo.observe(r,{subtree:true,childList:true,characterData:true});['reelTopic','hookInput','caption','cta'].forEach(id=>$(id)?.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(apply,100)}));setTimeout(apply,350)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
