(()=>{
'use strict';
const $=id=>document.getElementById(id),norm=s=>String(s??'').replace(/\s+/g,' ').trim(),low=s=>norm(s).toLowerCase();
const weak=/^(?:آهنگ خوبی بود|لایک کن منو|ممنون میشم فالو کنی منو|حس خوب|عالی بود|خوبه|نظر شما چیه|چه آهنگی|این آهنگ|music|song)$/i;
const topicWords=['ماشین','خودرو','پژو','پراید','سمند','دنا','رانندگی','غذا','آشپزی','رستوران','پیتزا','کیک','ورزش','تمرین','فیتنس','بدنسازی','باشگاه','موبایل','گوشی','تکنولوژی','لپ‌تاپ','گجت','اپلیکیشن','اندروید','آیفون','پول','درآمد','کسب و کار','اقتصاد','سرمایه','فروش','بازاریابی','سفر','گردشگری','ایرانگردی','هتل','طبیعت','آموزش','یادگیری','اکسل','لباس','استایل','مد','آرایش','زیبایی','گیم','بازی','گیمر','کتاب','فیلم','سریال','موسیقی','آهنگ'];
function validTopic(){const v=norm($('reelTopic')?.value);if(!v||weak.test(v))return false;return topicWords.some(k=>low(v).includes(low(k)))||v.length>=18}
function cleanVisibleText(){const root=$('findings');if(!root)return;for(const e of [...root.querySelectorAll('*')]){const t=norm(e.textContent);if(!t)continue;if(/^🔎\s*متن روی (?:ویدیو|تصویر)/.test(t)){e.textContent='🔎 متن معتبر روی تصویر شناسایی نشد؛ OCR نامعتبر نادیده گرفته شد.';break}if(/گفتار تشخیص‌داده‌شده/.test(t)&&(/\[Music\]|\bMusic\b|\bstrong man\b|\bbrave man\b/i.test(t))){e.textContent='🎙️ گفتار معتبر برای استفاده در قلاب تشخیص داده نشد؛ صدای موسیقی/رونویسی نامطمئن نادیده گرفته شد.';break}}}
function hardenTopic(){if(validTopic())return;const summary=$('summary');if(summary){const p=[...summary.querySelectorAll('*')].find(e=>/موضوع تشخیص‌داده‌شده:/.test(e.textContent||''));if(p)p.textContent='موضوع تشخیص‌داده‌شده: موضوع دقیق تشخیص داده نشد • اطمینان پایین • سیگنال موضوعی کافی وجود ندارد.'}const f=$('findings');if(f){const a=[...f.querySelectorAll('article')].find(x=>x.dataset.reellab==='intelligence');if(a){a.className='finding bad';a.textContent='';const b=document.createElement('b');b.textContent='🔴 موضوع با اطمینان کافی مشخص نشد';const p=document.createElement('p');p.textContent='متن‌هایی مثل «آهنگ خوبی بود؟» به‌تنهایی موضوع Reel نیستند؛ برای جلوگیری از هشتگ و کپشن اشتباه، یک جمله واقعی درباره محتوای ویدیو وارد کن.';a.append(b,p)}}const tags=$('hashtags');if(tags){tags.textContent='';const s=document.createElement('span');s.className='hashtag';s.textContent='موضوع نامشخص — هشتگ حدسی ساخته نشد';tags.append(s)}const hb=$('hooks');if(hb){hb.textContent='';['موضوع واقعی Reel را در ۳ ثانیه اول واضح کن.','نتیجه یا اتفاق اصلی را قبل از مقدمه نشان بده.','اگر متن یا گفتار معتبر داری، همان را به یک سؤال مشخص تبدیل کن.'].forEach((x,i)=>{const d=document.createElement('div');d.className='hook';const sm=document.createElement('small');sm.textContent='گزینه '+(i+1);const sp=document.createElement('span');sp.textContent=x;const btn=document.createElement('button');btn.type='button';btn.className='use-btn';btn.textContent='انتخاب این قلاب';btn.onclick=()=>{const h=$('hookInput');if(h){h.value=x;h.dispatchEvent(new Event('input',{bubbles:true}))}};d.append(sm,sp,btn);hb.append(d)})}}
function disableBadHashCopy(){const b=$('copyHashtagsBtn');if(b){b.disabled=true;b.textContent='📋 فعلاً هشتگ معتبر آماده نیست'}}
let busy=false,timer=0,last='';function apply(){if(busy)return;const key=[norm($('reelTopic')?.value),norm($('hookInput')?.value),norm($('caption')?.value),norm($('cta')?.value),$('results')?.innerText||''].join('|');if(key===last)return;last=key;busy=true;try{cleanVisibleText();hardenTopic();if(!validTopic())disableBadHashCopy()}finally{busy=false}}
function boot(){const r=$('results');if(!r)return;const mo=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(apply,80)});mo.observe(r,{subtree:true,childList:true,characterData:true});['reelTopic','hookInput','caption','cta'].forEach(id=>$(id)?.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(apply,80)}));setTimeout(apply,250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
