(()=>{
'use strict';
const $=id=>document.getElementById(id),norm=s=>String(s||'').replace(/\s+/g,' ').trim(),low=s=>norm(s).toLowerCase();
const topics=[
{keys:['ماشین','خودرو','پژو','پراید','سمند','دنا','تیبا','رانندگی','motorcycle','car'],name:'خودرو و ماشین',tags:['#خودرو','#ماشین','#رانندگی','#خودروی_کارکرده']},
{keys:['غذا','آشپزی','رستوران','پیتزا','کیک','دسر','pizza','cake','food'],name:'غذا و آشپزی',tags:['#غذا','#آشپزی','#فود','#غذای_خونگی']},
{keys:['ورزش','تمرین','فیتنس','بدنسازی','باشگاه','gym','fitness','workout'],name:'ورزش و فیتنس',tags:['#ورزش','#فیتنس','#تمرین','#بدنسازی']},
{keys:['موبایل','گوشی','تکنولوژی','لپ‌تاپ','گجت','اپلیکیشن','اندروید','آیفون','iphone','android','tech'],name:'موبایل و تکنولوژی',tags:['#تکنولوژی','#موبایل','#گجت','#ترفند_موبایل']},
{keys:['پول','درآمد','کسب و کار','کسب‌وکار','اقتصاد','سرمایه','فروش','بازاریابی','مشتری'],name:'کسب‌وکار و درآمد',tags:['#کسب_و_کار','#درآمد','#فروش','#بازاریابی']},
{keys:['سفر','گردشگری','ایرانگردی','هتل','ساحل','طبیعت','مسافرت','گردش','travel'],name:'سفر و گردشگری',tags:['#سفر','#گردشگری','#ایرانگردی','#مسافرت']},
{keys:['آموزش','یادگیری','آموز','اکسل','نکته','tutorial','learn'],name:'آموزش و یادگیری',tags:['#آموزش','#یادگیری','#نکات_کاربردی','#آموزش_آنلاین']},
{keys:['لباس','استایل','مد','فشن','آرایش','میکاپ','زیبایی','fashion','style'],name:'مد و زیبایی',tags:['#استایل','#مد','#فشن','#زیبایی']},
{keys:['گیم','بازی','گیمر','game','gaming'],name:'بازی و گیم',tags:['#گیم','#بازی','#گیمر']},
{keys:['کتاب','فیلم','سریال','موسیقی','آهنگ','movie','music','book'],name:'سرگرمی و فرهنگ',tags:['#سرگرمی','#موسیقی','#فیلم']}
];
function cleanSpeech(s){s=norm(s).replace(/\[(music|noise|applause|laughter)[^\]]*\]/gi,' ');const w=norm(s).split(/\s+/).filter(Boolean),o=[];for(const x of w)if(!o.length||low(o[o.length-1])!==low(x))o.push(x);s=norm(o.join(' '));if(!s||s.length<6||/^(i swear|music|thank you|thanks|yeah|yes|no|oh|uh|um|hmm)([ ,.]+(i swear|music|thank you|thanks|yeah|yes|no|oh|uh|um|hmm))*[.!?]*$/i.test(s))return '';const letters=(s.match(/[\p{L}]/gu)||[]).length;return letters/Math.max(1,s.length)<.45?'':s;}
function cleanOcr(s){const w=norm(s).split(/\s+/).filter(x=>x.length>=3&&/[\p{L}]/u.test(x)),o=[];for(const x of w)if(!o.some(y=>low(y)===low(x)))o.push(x);if(o.length<3)return '';return new Set(o.map(low)).size/o.length<.55?'':o.join(' ');}
function detect(manual,speech,ocr){const m=norm(manual);if(m.length>=4){const hit=topics.find(t=>t.keys.some(k=>low(m).includes(low(k))));return{name:hit?hit.name:m.slice(0,70),tags:hit?hit.tags:[],confidence:hit?'بالا':'متوسط',known:true,source:'توضیح کاربر'};}const all=low(`${speech} ${ocr}`);let best=null,score=0;for(const t of topics){let n=0;for(const k of t.keys)if(all.includes(low(k)))n+=k.length>=5?2:1;if(n>score){score=n;best=t;}}return best&&score>=3?{name:best.name,tags:best.tags,confidence:score>=5?'بالا':'متوسط',known:true,source:'سیگنال متنی'}:{name:'موضوع نامشخص',tags:[],confidence:'پایین',known:false,source:'سیگنال ناکافی'};}
function readSignals(){const r=$('results');if(!r)return{};const text=r.innerText||'',sm=text.match(/گفتار تشخیص‌داده‌شده\s*([\s\S]*?)(?=\n\s*(?:متن روی ویدیو|متن روی تصویر|👁️))/i),om=text.match(/متن روی ویدیو شناسایی‌شده\s*([\s\S]*?)(?=\n\s*(?:👁️|عناصر تصویری))/i);return{speech:cleanSpeech(sm?.[1]||''),ocr:cleanOcr(om?.[1]||'')};}
function score(topic,speech,ocr){let n=25;if(topic.known)n+=30;if(speech)n+=20;if(ocr)n+=10;if(norm($('hookInput')?.value))n+=15;return Math.min(100,n);}
function hooks(topic){if(!topic.known)return ['قلاب را از خود محتوای واقعی بساز؛ اول اتفاق اصلی را نشان بده.','با یک سؤال مشخص درباره اتفاق داخل ویدیو شروع کن.','مقدمه را حذف کن و در ۳ ثانیه اول نکته اصلی را نشان بده.'];const t=topic.name;return [`قبل از اینکه ردش کنی، اینو درباره ${t} ببین.`,`اگه ${t} برات مهمه، این نکته رو از دست نده.`,`یه نکته واقعی درباره ${t} که ارزش دیدن داره.`];}
function caption(topic,goal){if(!topic.known)return 'موضوع این ویدیو هنوز با اطمینان مشخص نشد.\n\nبرای اینکه کپشن الکی نسازیم، یک جمله درباره اتفاق اصلی Reel بنویس.';const end={reach:'اگه به درد یکی می‌خوره، براش بفرست.',followers:'اگه این مدل محتوا به کارت میاد، فالو کن.',engagement:'تو جای من بودی چی کار می‌کردی؟ بنویس.',sales:'اگه به کارت میاد، جزئیاتش رو ببین.'}[goal]||'نظرت رو بگو.';return `${topic.name}؛ کوتاه و بدون حاشیه.\n\n${end}`;}
function render(){const r=$('results');if(!r||r.hidden)return;const {speech,ocr}=readSignals(),topic=detect($('reelTopic')?.value,speech,ocr),g=$('goal')?.value||'reach',reliable=topic.known,sc=score(topic,speech,ocr);
const metric=$('metrics');if(metric){let box=[...metric.children].find(x=>/امتیاز|آمادگی/.test(x.innerText||''));if(!box){box=document.createElement('div');box.className='metric';metric.prepend(box);}box.textContent='';const b=document.createElement('b');b.textContent=`${sc}/100`;const s=document.createElement('span');s.textContent='امتیاز آمادگی Reel';box.append(b,s);}
const summary=$('summary');if(summary){const p=[...summary.querySelectorAll('*')].find(x=>/موضوع تشخیص‌داده‌شده:/.test(x.textContent||''));if(p)p.textContent=`موضوع تشخیص‌داده‌شده: ${reliable?topic.name:'موضوع دقیق تشخیص داده نشد'} • اطمینان ${topic.confidence} • ${topic.source}`;}
const f=$('findings');if(f){[...f.querySelectorAll('article')].forEach(a=>{if(/موضوع قابل اعتماد نیست|موضوع قابل استفاده است|قلاب از گفتار/i.test(a.innerText||''))a.remove();if(/متن روی ویدیو/i.test(a.innerText||'')&&!ocr){const p=a.querySelector('p');if(p)p.textContent='OCR نامعتبر تشخیص داده شد و در تولید محتوا استفاده نشد.';}});const a=document.createElement('article');a.className=`finding ${reliable?'ok':'bad'}`;const b=document.createElement('b');b.textContent=reliable?'🟢 موضوع قابل استفاده است':'🔴 موضوع قابل اعتماد نیست';const p=document.createElement('p');p.textContent=reliable?'موضوع از سیگنال متنی قابل اتکا استخراج شد.':'این نسخه عمداً از حدس‌زدن موضوع، کپشن و هشتگ جلوگیری می‌کند.';a.append(b,p);f.append(a);}
const hb=$('hooks');if(hb){hb.textContent='';hooks(topic).forEach((x,i)=>{const d=document.createElement('div');d.className=`hook${i===0?' recommended':''}`;const sm=document.createElement('small');sm.textContent=`گزینه ${i+1}`;const sp=document.createElement('span');sp.textContent=x;d.append(sm,sp);const btn=document.createElement('button');btn.type='button';btn.className='use-btn';btn.textContent='انتخاب این قلاب';btn.onclick=()=>{$('hookInput').value=x;d.classList.add('chosen');};d.append(btn);hb.append(d);});}
const cap=$('captionSuggestion');if(cap)cap.textContent=caption(topic,g);const reason=$('captionReason');if(reason)reason.textContent=reliable?'کپشن فقط از موضوع قابل اتکا ساخته شد؛ گفتار نامعتبر وارد متن نمی‌شود.':'کپشن حدسی تولید نمی‌شود؛ یک جمله از موضوع واقعی Reel بده.';
const tags=$('hashtags');if(tags){tags.textContent='';if(reliable)topic.tags.slice(0,5).forEach(x=>{const s=document.createElement('span');s.className='hashtag';s.textContent=x;tags.append(s);});else{const s=document.createElement('span');s.className='hashtag';s.textContent='هشتگ قابل اعتماد نداریم';tags.append(s);}}
const cs=$('ctaSuggestion');if(cs)cs.textContent={reach:'اگه به درد یکی می‌خوره، براش بفرست.',followers:'اگه این مدل محتوا به کارت میاد، فالو کن.',engagement:'تو چی فکر می‌کنی؟ توی کامنت بگو.',sales:'اگه برات مناسبه، جزئیاتش رو ببین.'}[g]||'نظرت رو بگو.';}
let last='',rendering=false,timer=0;function run(){const r=$('results');if(!r||r.hidden||rendering)return;const sig=(r.innerText||'').slice(0,5000);if(sig===last)return;last=sig;clearTimeout(timer);timer=setTimeout(()=>{rendering=true;try{render();}finally{rendering=false;last=(r.innerText||'').slice(0,5000);}},80);}new MutationObserver(run).observe(document.body,{subtree:true,childList:true,characterData:true});window.addEventListener('load',()=>setTimeout(run,300));
})();
