(()=>{
'use strict';
const $=id=>document.getElementById(id),N=s=>String(s??'').replace(/\s+/g,' ').trim(),L=s=>N(s).toLowerCase();
const MUSIC=/\[(?:music|noise|singing|instrumental|applause|laughter|silence|blank)[^\]]*\]|\b(?:music|song|soundtrack|instrumental|singing|chorus|beat)\b/i;
const GARBAGE=/^(?:i swear(?:\s+i swear)*|yeah(?:\s+yeah)*|yes(?:\s+yes)*|no(?:\s+no)*|oh(?:\s+oh)*|uh(?:\s+uh)*|um(?:\s+um)*|la la(?:\s+la la)*)[.!?]*$/i;
const GENERIC=/^(?:آهنگ خوبی بود|لایک کن منو|ممنون میشم فالو کنی منو|حس خوب|عالی بود|خوبه|نظر شما چیه|چه آهنگی|این آهنگ|music|song)$/i;
function validSpeech(v){v=N(v);if(!v||MUSIC.test(v)||GARBAGE.test(v))return false;const w=v.split(/\s+/).filter(Boolean);if(w.length<5)return false;const letters=(v.match(/[A-Za-z\p{L}]/gu)||[]).length;if(letters/Math.max(1,v.length)<.55)return false;const c={};w.forEach(x=>c[L(x)]=(c[L(x)]||0)+1);return Math.max(...Object.values(c))/w.length<=.4}
function validManualTopic(){const v=N($('reelTopic')?.value);if(!v||GENERIC.test(v)||v.length<8)return false;const keys=['ماشین','خودرو','پژو','پراید','رانندگی','غذا','آشپزی','رستوران','ورزش','تمرین','بدنسازی','موبایل','گوشی','تکنولوژی','اکسل','آموزش','سفر','هتل','طبیعت','لباس','استایل','مد','آرایش','گیم','بازی','کتاب','فیلم','سریال','موسیقی','آهنگ','درآمد','کسب و کار','فروش','بازاریابی'];return keys.some(k=>L(v).includes(k))||v.split(/\s+/).length>=5}
function replaceText(el,text){if(el&&N(el.textContent)!==text)el.textContent=text}
function repairFindings(){const f=$('findings');if(!f)return;for(const el of [...f.querySelectorAll('*')]){const t=N(el.textContent);if(!t)continue;if(/قلاب از گفتار\/متن استخراج شد/.test(t)){const q=t.match(/[«"]([^»"]+)[»"]/)?.[1]||'';if(!validSpeech(q)){replaceText(el,'🔴 قلاب معتبر از گفتار استخراج نشد\nموتور یک قطعه موسیقی/گفتار نامطمئن را قلاب حساب کرده بود؛ این سیگنال برای قلاب و موضوع قابل اعتماد نیست.')}}if(/🎙️\s*گفتار ویدیو شناسایی شد/.test(t)){const body=t.replace(/^🎙️\s*گفتار ویدیو شناسایی شد\s*/,'');if(!validSpeech(body))replaceText(el,'🎙️ گفتار معتبر برای تحلیل محتوا تشخیص داده نشد؛ سیگنال موسیقی/رونویسی نامطمئن کنار گذاشته شد.')}}}
function repairHooks(){const h=$('hooks');if(!h)return;const bad=[...h.querySelectorAll('.hook')].some(x=>{const t=N(x.textContent);return MUSIC.test(t)||GARBAGE.test(t)||/\b(?:i swear|yeah|song|music)\b/i.test(t)});if(!bad)return;h.textContent='';[['گزینه 1','قلاب را از اولین اتفاق واقعی Reel بساز؛ نه از موسیقی یا رونویسی نامطمئن.'],['گزینه 2','نتیجه یا اتفاق اصلی را در همان ۳ ثانیه اول نشان بده.'],['گزینه 3','اگر گفتار معتبر نداری، یک جمله واقعی درباره موضوع Reel وارد کن.']].forEach(([a,b])=>{const d=document.createElement('div');d.className='hook';const s=document.createElement('small');s.textContent=a;const p=document.createElement('span');p.textContent=b;const btn=document.createElement('button');btn.type='button';btn.className='use-btn';btn.textContent='انتخاب این قلاب';btn.onclick=()=>{const x=$('hookInput');if(x){x.value=b;x.dispatchEvent(new Event('input',{bubbles:true}))}};d.append(s,p,btn);h.append(d)})}
function repairCaption(){const c=$('captionSuggestion');if(!c)return;const t=N(c.textContent);if(MUSIC.test(t)||GARBAGE.test(t)||/\b(?:i swear|yeah|song|music)\b/i.test(t)){replaceText(c,'کپشن حدسی متوقف شد. برای کپشن دقیق، موضوع یا اتفاق اصلی Reel را وارد کن.');const r=$('captionReason');replaceText(r,'موتور از موسیقی یا رونویسی نامطمئن برای ساخت کپشن استفاده نمی‌کند.')}}
function repairTopic(){if(validManualTopic())return;const s=$('summary');if(s){const x=[...s.querySelectorAll('*')].find(e=>/موضوع تشخیص‌داده‌شده:/.test(N(e.textContent)));if(x)replaceText(x,'موضوع تشخیص‌داده‌شده: موضوع دقیق تشخیص داده نشد • اطمینان پایین • سیگنال موضوعی کافی وجود ندارد.')}const f=$('findings');if(f){const a=[...f.querySelectorAll('article')].find(x=>x.dataset.reellab==='intelligence');if(a){a.className='finding bad';a.textContent='';const b=document.createElement('b');b.textContent='🔴 موضوع با اطمینان کافی مشخص نشد';const p=document.createElement('p');p.textContent='موسیقی، جمله‌های کلی یا وجود یک «آدم» به‌تنهایی موضوع Reel نیست. برای خروجی دقیق، متن/قلاب واقعی یا توضیح مشخص محتوا لازم است.';a.append(b,p)}}const tags=$('hashtags');if(tags){tags.textContent='موضوع نامشخص — هشتگ حدسی ساخته نشد'}const c=$('captionSuggestion');if(c)replaceText(c,'کپشن حدسی متوقف شد. برای کپشن دقیق، موضوع یا اتفاق اصلی Reel را وارد کن.');const r=$('captionReason');if(r)replaceText(r,'سیگنال معتبر موضوعی وجود ندارد؛ موتور نباید کپشن یا هشتگ ساختگی تولید کند.')}}
function repairProvenance(){const f=$('findings');if(!f)return;for(const el of [...f.querySelectorAll('*')]){const t=N(el.textContent);if(/تحلیل تصویر، OCR و گفتار در مرورگر انجام شد/.test(t)){const has=validManualTopic();if(!has)replaceText(el,t.replace('تحلیل تصویر، OCR و گفتار در مرورگر انجام شد.','تحلیل سیگنال‌های مرورگر انجام شد؛ هیچ مدل معنایی قابل اتکایی موضوع را تأیید نکرد.'))}}}
let busy=false,last='';function run(){if(busy)return;const key=($('results')?.innerText||'')+'|'+N($('reelTopic')?.value);if(key===last)return;last=key;busy=true;try{repairFindings();repairHooks();repairCaption();repairTopic();repairProvenance()}finally{busy=false}}
function boot(){const r=$('results');if(!r)return;const mo=new MutationObserver(()=>{clearTimeout(window.__reellabV6);window.__reellabV6=setTimeout(run,80)});mo.observe(r,{subtree:true,childList:true,characterData:true});['reelTopic','hookInput','caption','cta'].forEach(id=>$(id)?.addEventListener('input',()=>setTimeout(run,50)));setTimeout(run,250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
